package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code cpp} from tree-sitter {@code node-types.json}.
 */
public enum CppNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ABSTRACT_ARRAY_DECLARATOR("abstract_array_declarator"),
    ABSTRACT_DECLARATOR("_abstract_declarator"),
    ABSTRACT_FUNCTION_DECLARATOR("abstract_function_declarator"),
    ABSTRACT_PARENTHESIZED_DECLARATOR("abstract_parenthesized_declarator"),
    ABSTRACT_POINTER_DECLARATOR("abstract_pointer_declarator"),
    ABSTRACT_REFERENCE_DECLARATOR("abstract_reference_declarator"),
    ACCESS_SPECIFIER("access_specifier"),
    ALIAS_DECLARATION("alias_declaration"),
    ALIGNAS_QUALIFIER("alignas_qualifier"),
    ALIGNOF_EXPRESSION("alignof_expression"),
    ARGUMENT_LIST("argument_list"),
    ARRAY_DECLARATOR("array_declarator"),
    ASSIGNMENT_EXPRESSION("assignment_expression"),
    ATTRIBUTE("attribute"),
    ATTRIBUTED_DECLARATOR("attributed_declarator"),
    ATTRIBUTED_STATEMENT("attributed_statement"),
    ATTRIBUTE_DECLARATION("attribute_declaration"),
    ATTRIBUTE_SPECIFIER("attribute_specifier"),
    AUTO("auto"),
    BASE_CLASS_CLAUSE("base_class_clause"),
    BINARY_EXPRESSION("binary_expression"),
    BITFIELD_CLAUSE("bitfield_clause"),
    BREAK_STATEMENT("break_statement"),
    CALL_EXPRESSION("call_expression"),
    CASE_STATEMENT("case_statement"),
    CAST_EXPRESSION("cast_expression"),
    CATCH_CLAUSE("catch_clause"),
    CHARACTER("character"),
    CHAR_LITERAL("char_literal"),
    CLASS_SPECIFIER("class_specifier"),
    COMMA_EXPRESSION("comma_expression"),
    COMMENT("comment"),
    COMPOUND_LITERAL_EXPRESSION("compound_literal_expression"),
    COMPOUND_REQUIREMENT("compound_requirement"),
    COMPOUND_STATEMENT("compound_statement"),
    CONCATENATED_STRING("concatenated_string"),
    CONCEPT_DEFINITION("concept_definition"),
    CONDITIONAL_EXPRESSION("conditional_expression"),
    CONDITION_CLAUSE("condition_clause"),
    CONSTRAINT_CONJUNCTION("constraint_conjunction"),
    CONSTRAINT_DISJUNCTION("constraint_disjunction"),
    CONTINUE_STATEMENT("continue_statement"),
    CO_AWAIT_EXPRESSION("co_await_expression"),
    CO_RETURN_STATEMENT("co_return_statement"),
    CO_YIELD_STATEMENT("co_yield_statement"),
    DECLARATION("declaration"),
    DECLARATION_LIST("declaration_list"),
    DECLARATOR("_declarator"),
    DECLTYPE("decltype"),
    DEFAULT_METHOD_CLAUSE("default_method_clause"),
    DELETE_EXPRESSION("delete_expression"),
    DELETE_METHOD_CLAUSE("delete_method_clause"),
    DEPENDENT_NAME("dependent_name"),
    DEPENDENT_TYPE("dependent_type"),
    DESTRUCTOR_NAME("destructor_name"),
    DO_STATEMENT("do_statement"),
    ELSE_CLAUSE("else_clause"),
    ENUMERATOR("enumerator"),
    ENUMERATOR_LIST("enumerator_list"),
    ENUM_SPECIFIER("enum_specifier"),
    ESCAPE_SEQUENCE("escape_sequence"),
    EXPLICIT_FUNCTION_SPECIFIER("explicit_function_specifier"),
    EXPRESSION("expression"),
    EXPRESSION_STATEMENT("expression_statement"),
    EXTENSION_EXPRESSION("extension_expression"),
    FALSE("false"),
    FIELD_DECLARATION("field_declaration"),
    FIELD_DECLARATION_LIST("field_declaration_list"),
    FIELD_DECLARATOR("_field_declarator"),
    FIELD_DESIGNATOR("field_designator"),
    FIELD_EXPRESSION("field_expression"),
    FIELD_IDENTIFIER("field_identifier"),
    FIELD_INITIALIZER("field_initializer"),
    FIELD_INITIALIZER_LIST("field_initializer_list"),
    FOLD_EXPRESSION("fold_expression"),
    FOR_RANGE_LOOP("for_range_loop"),
    FOR_STATEMENT("for_statement"),
    FRIEND_DECLARATION("friend_declaration"),
    FUNCTION_DECLARATOR("function_declarator"),
    FUNCTION_DEFINITION("function_definition"),
    GENERIC_EXPRESSION("generic_expression"),
    GNU_ASM_CLOBBER_LIST("gnu_asm_clobber_list"),
    GNU_ASM_EXPRESSION("gnu_asm_expression"),
    GNU_ASM_GOTO_LIST("gnu_asm_goto_list"),
    GNU_ASM_INPUT_OPERAND("gnu_asm_input_operand"),
    GNU_ASM_INPUT_OPERAND_LIST("gnu_asm_input_operand_list"),
    GNU_ASM_OUTPUT_OPERAND("gnu_asm_output_operand"),
    GNU_ASM_OUTPUT_OPERAND_LIST("gnu_asm_output_operand_list"),
    GNU_ASM_QUALIFIER("gnu_asm_qualifier"),
    GOTO_STATEMENT("goto_statement"),
    IDENTIFIER("identifier"),
    IF_STATEMENT("if_statement"),
    INITIALIZER_LIST("initializer_list"),
    INITIALIZER_PAIR("initializer_pair"),
    INIT_DECLARATOR("init_declarator"),
    INIT_STATEMENT("init_statement"),
    LABELED_STATEMENT("labeled_statement"),
    LAMBDA_CAPTURE_INITIALIZER("lambda_capture_initializer"),
    LAMBDA_CAPTURE_SPECIFIER("lambda_capture_specifier"),
    LAMBDA_DEFAULT_CAPTURE("lambda_default_capture"),
    LAMBDA_EXPRESSION("lambda_expression"),
    LINKAGE_SPECIFICATION("linkage_specification"),
    LITERAL_SUFFIX("literal_suffix"),
    MS_BASED_MODIFIER("ms_based_modifier"),
    MS_CALL_MODIFIER("ms_call_modifier"),
    MS_DECLSPEC_MODIFIER("ms_declspec_modifier"),
    MS_POINTER_MODIFIER("ms_pointer_modifier"),
    MS_RESTRICT_MODIFIER("ms_restrict_modifier"),
    MS_SIGNED_PTR_MODIFIER("ms_signed_ptr_modifier"),
    MS_UNALIGNED_PTR_MODIFIER("ms_unaligned_ptr_modifier"),
    MS_UNSIGNED_PTR_MODIFIER("ms_unsigned_ptr_modifier"),
    NAMESPACE_ALIAS_DEFINITION("namespace_alias_definition"),
    NAMESPACE_DEFINITION("namespace_definition"),
    NAMESPACE_IDENTIFIER("namespace_identifier"),
    NESTED_NAMESPACE_SPECIFIER("nested_namespace_specifier"),
    NEW_DECLARATOR("new_declarator"),
    NEW_EXPRESSION("new_expression"),
    NOEXCEPT("noexcept"),
    NULL("null"),
    NUMBER_LITERAL("number_literal"),
    OFFSETOF_EXPRESSION("offsetof_expression"),
    OPERATOR_CAST("operator_cast"),
    OPERATOR_NAME("operator_name"),
    OPTIONAL_PARAMETER_DECLARATION("optional_parameter_declaration"),
    OPTIONAL_TYPE_PARAMETER_DECLARATION("optional_type_parameter_declaration"),
    PARAMETER_DECLARATION("parameter_declaration"),
    PARAMETER_LIST("parameter_list"),
    PARAMETER_PACK_EXPANSION("parameter_pack_expansion"),
    PARENTHESIZED_DECLARATOR("parenthesized_declarator"),
    PARENTHESIZED_EXPRESSION("parenthesized_expression"),
    PLACEHOLDER_TYPE_SPECIFIER("placeholder_type_specifier"),
    POINTER_DECLARATOR("pointer_declarator"),
    POINTER_EXPRESSION("pointer_expression"),
    POINTER_TYPE_DECLARATOR("pointer_type_declarator"),
    PREPROC_ARG("preproc_arg"),
    PREPROC_CALL("preproc_call"),
    PREPROC_DEF("preproc_def"),
    PREPROC_DEFINED("preproc_defined"),
    PREPROC_DIRECTIVE("preproc_directive"),
    PREPROC_ELIF("preproc_elif"),
    PREPROC_ELIFDEF("preproc_elifdef"),
    PREPROC_ELSE("preproc_else"),
    PREPROC_FUNCTION_DEF("preproc_function_def"),
    PREPROC_IF("preproc_if"),
    PREPROC_IFDEF("preproc_ifdef"),
    PREPROC_INCLUDE("preproc_include"),
    PREPROC_PARAMS("preproc_params"),
    PRIMITIVE_TYPE("primitive_type"),
    PURE_VIRTUAL_CLAUSE("pure_virtual_clause"),
    QUALIFIED_IDENTIFIER("qualified_identifier"),
    RAW_STRING_CONTENT("raw_string_content"),
    RAW_STRING_DELIMITER("raw_string_delimiter"),
    RAW_STRING_LITERAL("raw_string_literal"),
    REFERENCE_DECLARATOR("reference_declarator"),
    REF_QUALIFIER("ref_qualifier"),
    REQUIREMENT_SEQ("requirement_seq"),
    REQUIRES_CLAUSE("requires_clause"),
    REQUIRES_EXPRESSION("requires_expression"),
    RETURN_STATEMENT("return_statement"),
    SEH_EXCEPT_CLAUSE("seh_except_clause"),
    SEH_FINALLY_CLAUSE("seh_finally_clause"),
    SEH_LEAVE_STATEMENT("seh_leave_statement"),
    SEH_TRY_STATEMENT("seh_try_statement"),
    SIMPLE_REQUIREMENT("simple_requirement"),
    SIZED_TYPE_SPECIFIER("sized_type_specifier"),
    SIZEOF_EXPRESSION("sizeof_expression"),
    STATEMENT("statement"),
    STATEMENT_IDENTIFIER("statement_identifier"),
    STATIC_ASSERT_DECLARATION("static_assert_declaration"),
    STORAGE_CLASS_SPECIFIER("storage_class_specifier"),
    STRING_CONTENT("string_content"),
    STRING_LITERAL("string_literal"),
    STRUCTURED_BINDING_DECLARATOR("structured_binding_declarator"),
    STRUCT_SPECIFIER("struct_specifier"),
    SUBSCRIPT_ARGUMENT_LIST("subscript_argument_list"),
    SUBSCRIPT_DESIGNATOR("subscript_designator"),
    SUBSCRIPT_EXPRESSION("subscript_expression"),
    SUBSCRIPT_RANGE_DESIGNATOR("subscript_range_designator"),
    SWITCH_STATEMENT("switch_statement"),
    SYSTEM_LIB_STRING("system_lib_string"),
    TEMPLATE_ARGUMENT_LIST("template_argument_list"),
    TEMPLATE_DECLARATION("template_declaration"),
    TEMPLATE_FUNCTION("template_function"),
    TEMPLATE_INSTANTIATION("template_instantiation"),
    TEMPLATE_METHOD("template_method"),
    TEMPLATE_PARAMETER_LIST("template_parameter_list"),
    TEMPLATE_TEMPLATE_PARAMETER_DECLARATION("template_template_parameter_declaration"),
    TEMPLATE_TYPE("template_type"),
    THIS_("this"),
    THROW_SPECIFIER("throw_specifier"),
    THROW_STATEMENT("throw_statement"),
    TRAILING_RETURN_TYPE("trailing_return_type"),
    TRANSLATION_UNIT("translation_unit"),
    TRUE("true"),
    TRY_STATEMENT("try_statement"),
    TYPE_DECLARATOR("_type_declarator"),
    TYPE_DEFINITION("type_definition"),
    TYPE_DESCRIPTOR("type_descriptor"),
    TYPE_IDENTIFIER("type_identifier"),
    TYPE_PARAMETER_DECLARATION("type_parameter_declaration"),
    TYPE_QUALIFIER("type_qualifier"),
    TYPE_REQUIREMENT("type_requirement"),
    TYPE_SPECIFIER("type_specifier"),
    UNARY_EXPRESSION("unary_expression"),
    UNION_SPECIFIER("union_specifier"),
    UPDATE_EXPRESSION("update_expression"),
    USER_DEFINED_LITERAL("user_defined_literal"),
    USING_DECLARATION("using_declaration"),
    VARIADIC_DECLARATOR("variadic_declarator"),
    VARIADIC_PARAMETER_DECLARATION("variadic_parameter_declaration"),
    VARIADIC_TYPE_PARAMETER_DECLARATION("variadic_type_parameter_declaration"),
    VIRTUAL_SPECIFIER("virtual_specifier"),
    WHILE_STATEMENT("while_statement");

    public static final Set<CppNodeType> ABSTRACT_DECLARATOR_SET = Set.of(
            ABSTRACT_ARRAY_DECLARATOR,
            ABSTRACT_FUNCTION_DECLARATOR,
            ABSTRACT_PARENTHESIZED_DECLARATOR,
            ABSTRACT_POINTER_DECLARATOR,
            ABSTRACT_REFERENCE_DECLARATOR);
    public static final Set<CppNodeType> DECLARATOR_SET = Set.of(
            ARRAY_DECLARATOR,
            ATTRIBUTED_DECLARATOR,
            DESTRUCTOR_NAME,
            FUNCTION_DECLARATOR,
            IDENTIFIER,
            OPERATOR_NAME,
            PARENTHESIZED_DECLARATOR,
            POINTER_DECLARATOR,
            QUALIFIED_IDENTIFIER,
            REFERENCE_DECLARATOR,
            STRUCTURED_BINDING_DECLARATOR,
            TEMPLATE_FUNCTION);
    public static final Set<CppNodeType> EXPRESSION_SET = Set.of(
            ALIGNOF_EXPRESSION,
            ASSIGNMENT_EXPRESSION,
            BINARY_EXPRESSION,
            CALL_EXPRESSION,
            CAST_EXPRESSION,
            CHAR_LITERAL,
            COMPOUND_LITERAL_EXPRESSION,
            CONCATENATED_STRING,
            CONDITIONAL_EXPRESSION,
            CO_AWAIT_EXPRESSION,
            DELETE_EXPRESSION,
            EXTENSION_EXPRESSION,
            FALSE,
            FIELD_EXPRESSION,
            FOLD_EXPRESSION,
            GENERIC_EXPRESSION,
            GNU_ASM_EXPRESSION,
            IDENTIFIER,
            LAMBDA_EXPRESSION,
            NEW_EXPRESSION,
            NULL,
            NUMBER_LITERAL,
            OFFSETOF_EXPRESSION,
            PARAMETER_PACK_EXPANSION,
            PARENTHESIZED_EXPRESSION,
            POINTER_EXPRESSION,
            QUALIFIED_IDENTIFIER,
            RAW_STRING_LITERAL,
            REQUIRES_CLAUSE,
            REQUIRES_EXPRESSION,
            SIZEOF_EXPRESSION,
            STRING_LITERAL,
            SUBSCRIPT_EXPRESSION,
            TEMPLATE_FUNCTION,
            THIS_,
            TRUE,
            UNARY_EXPRESSION,
            UPDATE_EXPRESSION,
            USER_DEFINED_LITERAL);
    public static final Set<CppNodeType> FIELD_DECLARATOR_SET = Set.of(
            ARRAY_DECLARATOR,
            ATTRIBUTED_DECLARATOR,
            FIELD_IDENTIFIER,
            FUNCTION_DECLARATOR,
            OPERATOR_NAME,
            PARENTHESIZED_DECLARATOR,
            POINTER_DECLARATOR,
            REFERENCE_DECLARATOR,
            TEMPLATE_METHOD);
    public static final Set<CppNodeType> STATEMENT_SET = Set.of(
            ATTRIBUTED_STATEMENT,
            BREAK_STATEMENT,
            CASE_STATEMENT,
            COMPOUND_STATEMENT,
            CONTINUE_STATEMENT,
            CO_RETURN_STATEMENT,
            CO_YIELD_STATEMENT,
            DO_STATEMENT,
            EXPRESSION_STATEMENT,
            FOR_RANGE_LOOP,
            FOR_STATEMENT,
            GOTO_STATEMENT,
            IF_STATEMENT,
            LABELED_STATEMENT,
            RETURN_STATEMENT,
            SEH_LEAVE_STATEMENT,
            SEH_TRY_STATEMENT,
            SWITCH_STATEMENT,
            THROW_STATEMENT,
            TRY_STATEMENT,
            WHILE_STATEMENT);
    public static final Set<CppNodeType> TYPE_DECLARATOR_SET = Set.of(
            ARRAY_DECLARATOR,
            ATTRIBUTED_DECLARATOR,
            FUNCTION_DECLARATOR,
            PARENTHESIZED_DECLARATOR,
            POINTER_DECLARATOR,
            PRIMITIVE_TYPE,
            REFERENCE_DECLARATOR,
            TYPE_IDENTIFIER);
    public static final Set<CppNodeType> TYPE_SPECIFIER_SET = Set.of(
            CLASS_SPECIFIER,
            DECLTYPE,
            DEPENDENT_TYPE,
            ENUM_SPECIFIER,
            PLACEHOLDER_TYPE_SPECIFIER,
            PRIMITIVE_TYPE,
            QUALIFIED_IDENTIFIER,
            SIZED_TYPE_SPECIFIER,
            STRUCT_SPECIFIER,
            TEMPLATE_TYPE,
            TYPE_IDENTIFIER,
            UNION_SPECIFIER);

    private final @Nullable String type;

    CppNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static CppNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static CppNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        CppNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, CppNodeType> LOOKUP = initLookup();

    private static Map<String, CppNodeType> initLookup() {
        HashMap<String, CppNodeType> m = new HashMap<>();
        for (CppNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
