package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code rust} from tree-sitter {@code node-types.json}.
 */
public enum RustNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ABSTRACT_TYPE("abstract_type"),
    ARGUMENTS("arguments"),
    ARRAY_EXPRESSION("array_expression"),
    ARRAY_TYPE("array_type"),
    ASSIGNMENT_EXPRESSION("assignment_expression"),
    ASSOCIATED_TYPE("associated_type"),
    ASYNC_BLOCK("async_block"),
    ATTRIBUTE("attribute"),
    ATTRIBUTE_ITEM("attribute_item"),
    AWAIT_EXPRESSION("await_expression"),
    BASE_FIELD_INITIALIZER("base_field_initializer"),
    BINARY_EXPRESSION("binary_expression"),
    BLOCK("block"),
    BLOCK_COMMENT("block_comment"),
    BOOLEAN_LITERAL("boolean_literal"),
    BOUNDED_TYPE("bounded_type"),
    BRACKETED_TYPE("bracketed_type"),
    BREAK_EXPRESSION("break_expression"),
    CALL_EXPRESSION("call_expression"),
    CAPTURED_PATTERN("captured_pattern"),
    CHAR_LITERAL("char_literal"),
    CLOSURE_EXPRESSION("closure_expression"),
    CLOSURE_PARAMETERS("closure_parameters"),
    COMPOUND_ASSIGNMENT_EXPR("compound_assignment_expr"),
    CONST_BLOCK("const_block"),
    CONST_ITEM("const_item"),
    CONST_PARAMETER("const_parameter"),
    CONTINUE_EXPRESSION("continue_expression"),
    CRATE("crate"),
    DECLARATION_LIST("declaration_list"),
    DECLARATION_STATEMENT("_declaration_statement"),
    DOC_COMMENT("doc_comment"),
    DYNAMIC_TYPE("dynamic_type"),
    ELSE_CLAUSE("else_clause"),
    EMPTY_STATEMENT("empty_statement"),
    ENUM_ITEM("enum_item"),
    ENUM_VARIANT("enum_variant"),
    ENUM_VARIANT_LIST("enum_variant_list"),
    ESCAPE_SEQUENCE("escape_sequence"),
    EXPRESSION("_expression"),
    EXPRESSION_STATEMENT("expression_statement"),
    EXTERN_CRATE_DECLARATION("extern_crate_declaration"),
    EXTERN_MODIFIER("extern_modifier"),
    FIELD_DECLARATION("field_declaration"),
    FIELD_DECLARATION_LIST("field_declaration_list"),
    FIELD_EXPRESSION("field_expression"),
    FIELD_IDENTIFIER("field_identifier"),
    FIELD_INITIALIZER("field_initializer"),
    FIELD_INITIALIZER_LIST("field_initializer_list"),
    FIELD_PATTERN("field_pattern"),
    FLOAT_LITERAL("float_literal"),
    FOREIGN_MOD_ITEM("foreign_mod_item"),
    FOR_EXPRESSION("for_expression"),
    FOR_LIFETIMES("for_lifetimes"),
    FRAGMENT_SPECIFIER("fragment_specifier"),
    FUNCTION_ITEM("function_item"),
    FUNCTION_MODIFIERS("function_modifiers"),
    FUNCTION_SIGNATURE_ITEM("function_signature_item"),
    FUNCTION_TYPE("function_type"),
    GENERIC_FUNCTION("generic_function"),
    GENERIC_PATTERN("generic_pattern"),
    GENERIC_TYPE("generic_type"),
    GENERIC_TYPE_WITH_TURBOFISH("generic_type_with_turbofish"),
    GEN_BLOCK("gen_block"),
    HIGHER_RANKED_TRAIT_BOUND("higher_ranked_trait_bound"),
    IDENTIFIER("identifier"),
    IF_EXPRESSION("if_expression"),
    IMPL_ITEM("impl_item"),
    INDEX_EXPRESSION("index_expression"),
    INNER_ATTRIBUTE_ITEM("inner_attribute_item"),
    INNER_DOC_COMMENT_MARKER("inner_doc_comment_marker"),
    INTEGER_LITERAL("integer_literal"),
    LABEL("label"),
    LET_CHAIN("let_chain"),
    LET_CONDITION("let_condition"),
    LET_DECLARATION("let_declaration"),
    LIFETIME("lifetime"),
    LIFETIME_PARAMETER("lifetime_parameter"),
    LINE_COMMENT("line_comment"),
    LITERAL("_literal"),
    LITERAL_PATTERN("_literal_pattern"),
    LOOP_EXPRESSION("loop_expression"),
    MACRO_DEFINITION("macro_definition"),
    MACRO_INVOCATION("macro_invocation"),
    MACRO_RULE("macro_rule"),
    MATCH_ARM("match_arm"),
    MATCH_BLOCK("match_block"),
    MATCH_EXPRESSION("match_expression"),
    MATCH_PATTERN("match_pattern"),
    METAVARIABLE("metavariable"),
    MOD_ITEM("mod_item"),
    MUTABLE_SPECIFIER("mutable_specifier"),
    MUT_PATTERN("mut_pattern"),
    NEGATIVE_LITERAL("negative_literal"),
    NEVER_TYPE("never_type"),
    ORDERED_FIELD_DECLARATION_LIST("ordered_field_declaration_list"),
    OR_PATTERN("or_pattern"),
    OUTER_DOC_COMMENT_MARKER("outer_doc_comment_marker"),
    PARAMETER("parameter"),
    PARAMETERS("parameters"),
    PARENTHESIZED_EXPRESSION("parenthesized_expression"),
    PATTERN("_pattern"),
    POINTER_TYPE("pointer_type"),
    PRIMITIVE_TYPE("primitive_type"),
    QUALIFIED_TYPE("qualified_type"),
    RANGE_EXPRESSION("range_expression"),
    RANGE_PATTERN("range_pattern"),
    RAW_STRING_LITERAL("raw_string_literal"),
    REFERENCE_EXPRESSION("reference_expression"),
    REFERENCE_PATTERN("reference_pattern"),
    REFERENCE_TYPE("reference_type"),
    REF_PATTERN("ref_pattern"),
    REMAINING_FIELD_PATTERN("remaining_field_pattern"),
    REMOVED_TRAIT_BOUND("removed_trait_bound"),
    RETURN_EXPRESSION("return_expression"),
    SCOPED_IDENTIFIER("scoped_identifier"),
    SCOPED_TYPE_IDENTIFIER("scoped_type_identifier"),
    SCOPED_USE_LIST("scoped_use_list"),
    SELF("self"),
    SELF_PARAMETER("self_parameter"),
    SHEBANG("shebang"),
    SHORTHAND_FIELD_IDENTIFIER("shorthand_field_identifier"),
    SHORTHAND_FIELD_INITIALIZER("shorthand_field_initializer"),
    SLICE_PATTERN("slice_pattern"),
    SOURCE_FILE("source_file"),
    STATIC_ITEM("static_item"),
    STRING_CONTENT("string_content"),
    STRING_LITERAL("string_literal"),
    STRUCT_EXPRESSION("struct_expression"),
    STRUCT_ITEM("struct_item"),
    STRUCT_PATTERN("struct_pattern"),
    SUPER_("super"),
    TOKEN_BINDING_PATTERN("token_binding_pattern"),
    TOKEN_REPETITION("token_repetition"),
    TOKEN_REPETITION_PATTERN("token_repetition_pattern"),
    TOKEN_TREE("token_tree"),
    TOKEN_TREE_PATTERN("token_tree_pattern"),
    TRAIT_BOUNDS("trait_bounds"),
    TRAIT_ITEM("trait_item"),
    TRY_BLOCK("try_block"),
    TRY_EXPRESSION("try_expression"),
    TUPLE_EXPRESSION("tuple_expression"),
    TUPLE_PATTERN("tuple_pattern"),
    TUPLE_STRUCT_PATTERN("tuple_struct_pattern"),
    TUPLE_TYPE("tuple_type"),
    TYPE("_type"),
    TYPE_ARGUMENTS("type_arguments"),
    TYPE_BINDING("type_binding"),
    TYPE_CAST_EXPRESSION("type_cast_expression"),
    TYPE_IDENTIFIER("type_identifier"),
    TYPE_ITEM("type_item"),
    TYPE_PARAMETER("type_parameter"),
    TYPE_PARAMETERS("type_parameters"),
    UNARY_EXPRESSION("unary_expression"),
    UNION_ITEM("union_item"),
    UNIT_EXPRESSION("unit_expression"),
    UNIT_TYPE("unit_type"),
    UNSAFE_BLOCK("unsafe_block"),
    USE_AS_CLAUSE("use_as_clause"),
    USE_BOUNDS("use_bounds"),
    USE_DECLARATION("use_declaration"),
    USE_LIST("use_list"),
    USE_WILDCARD("use_wildcard"),
    VARIADIC_PARAMETER("variadic_parameter"),
    VISIBILITY_MODIFIER("visibility_modifier"),
    WHERE_CLAUSE("where_clause"),
    WHERE_PREDICATE("where_predicate"),
    WHILE_EXPRESSION("while_expression"),
    YIELD_EXPRESSION("yield_expression");

    public static final Set<RustNodeType> DECLARATION_STATEMENT_SET = Set.of(
            ASSOCIATED_TYPE,
            ATTRIBUTE_ITEM,
            CONST_ITEM,
            EMPTY_STATEMENT,
            ENUM_ITEM,
            EXTERN_CRATE_DECLARATION,
            FOREIGN_MOD_ITEM,
            FUNCTION_ITEM,
            FUNCTION_SIGNATURE_ITEM,
            IMPL_ITEM,
            INNER_ATTRIBUTE_ITEM,
            LET_DECLARATION,
            MACRO_DEFINITION,
            MACRO_INVOCATION,
            MOD_ITEM,
            STATIC_ITEM,
            STRUCT_ITEM,
            TRAIT_ITEM,
            TYPE_ITEM,
            UNION_ITEM,
            USE_DECLARATION);
    public static final Set<RustNodeType> EXPRESSION_SET = Set.of(
            ARRAY_EXPRESSION,
            ASSIGNMENT_EXPRESSION,
            ASYNC_BLOCK,
            AWAIT_EXPRESSION,
            BINARY_EXPRESSION,
            BLOCK,
            BREAK_EXPRESSION,
            CALL_EXPRESSION,
            CLOSURE_EXPRESSION,
            COMPOUND_ASSIGNMENT_EXPR,
            CONST_BLOCK,
            CONTINUE_EXPRESSION,
            FIELD_EXPRESSION,
            FOR_EXPRESSION,
            GENERIC_FUNCTION,
            GEN_BLOCK,
            IDENTIFIER,
            IF_EXPRESSION,
            INDEX_EXPRESSION,
            LITERAL,
            LOOP_EXPRESSION,
            MACRO_INVOCATION,
            MATCH_EXPRESSION,
            METAVARIABLE,
            PARENTHESIZED_EXPRESSION,
            RANGE_EXPRESSION,
            REFERENCE_EXPRESSION,
            RETURN_EXPRESSION,
            SCOPED_IDENTIFIER,
            SELF,
            STRUCT_EXPRESSION,
            TRY_BLOCK,
            TRY_EXPRESSION,
            TUPLE_EXPRESSION,
            TYPE_CAST_EXPRESSION,
            UNARY_EXPRESSION,
            UNIT_EXPRESSION,
            UNSAFE_BLOCK,
            WHILE_EXPRESSION,
            YIELD_EXPRESSION);
    public static final Set<RustNodeType> LITERAL_PATTERN_SET = Set.of(
            BOOLEAN_LITERAL,
            CHAR_LITERAL,
            FLOAT_LITERAL,
            INTEGER_LITERAL,
            NEGATIVE_LITERAL,
            RAW_STRING_LITERAL,
            STRING_LITERAL);
    public static final Set<RustNodeType> LITERAL_SET =
            Set.of(BOOLEAN_LITERAL, CHAR_LITERAL, FLOAT_LITERAL, INTEGER_LITERAL, RAW_STRING_LITERAL, STRING_LITERAL);
    public static final Set<RustNodeType> PATTERN_SET = Set.of(
            CAPTURED_PATTERN,
            CONST_BLOCK,
            GENERIC_PATTERN,
            IDENTIFIER,
            LITERAL_PATTERN,
            MACRO_INVOCATION,
            MUT_PATTERN,
            OR_PATTERN,
            RANGE_PATTERN,
            REFERENCE_PATTERN,
            REF_PATTERN,
            REMAINING_FIELD_PATTERN,
            SCOPED_IDENTIFIER,
            SLICE_PATTERN,
            STRUCT_PATTERN,
            TUPLE_PATTERN,
            TUPLE_STRUCT_PATTERN);
    public static final Set<RustNodeType> TYPE_SET = Set.of(
            ABSTRACT_TYPE,
            ARRAY_TYPE,
            BOUNDED_TYPE,
            DYNAMIC_TYPE,
            FUNCTION_TYPE,
            GENERIC_TYPE,
            MACRO_INVOCATION,
            METAVARIABLE,
            NEVER_TYPE,
            POINTER_TYPE,
            PRIMITIVE_TYPE,
            REFERENCE_TYPE,
            REMOVED_TRAIT_BOUND,
            SCOPED_TYPE_IDENTIFIER,
            TUPLE_TYPE,
            TYPE_IDENTIFIER,
            UNIT_TYPE);

    private final @Nullable String type;

    RustNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static RustNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static RustNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        RustNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, RustNodeType> LOOKUP = initLookup();

    private static Map<String, RustNodeType> initLookup() {
        HashMap<String, RustNodeType> m = new HashMap<>();
        for (RustNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
