dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation project(':tree-sitter-json')
}

tasks.named('downloadSource') {

}

tasks.named('buildNative') {
    additionalCFiles = downloadSource.srcDir.files("lib/src/lib.c")
    additionalIncludeDirs = project.files(downloadSource.srcDir.dir("lib/src"))
}