tasks.named('downloadSource') {
    url = "https://github.com/tree-sitter/tree-sitter-verilog/archive/refs/tags/v${upstreamVersion}.zip"
}

tasks.named("buildNative") {
    def newSrcDir = downloadDir.dir("tree-sitter-verilog-${upstreamVersion}/src")
    additionalCFiles = newSrcDir.asFileTree.matching {
        include("**/*.c")
        include("**/*.cpp")
    }
    additionalIncludeDirs = project.files(newSrcDir)
}