package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code c-sharp} from tree-sitter {@code node-types.json}.
 */
public enum CSharpNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ACCESSOR_DECLARATION("accessor_declaration"),
    ACCESSOR_LIST("accessor_list"),
    ALIAS_QUALIFIED_NAME("alias_qualified_name"),
    AND_PATTERN("and_pattern"),
    ANONYMOUS_METHOD_EXPRESSION("anonymous_method_expression"),
    ANONYMOUS_OBJECT_CREATION_EXPRESSION("anonymous_object_creation_expression"),
    ARGUMENT("argument"),
    ARGUMENT_LIST("argument_list"),
    ARRAY_CREATION_EXPRESSION("array_creation_expression"),
    ARRAY_RANK_SPECIFIER("array_rank_specifier"),
    ARRAY_TYPE("array_type"),
    ARROW_EXPRESSION_CLAUSE("arrow_expression_clause"),
    ASSIGNMENT_EXPRESSION("assignment_expression"),
    AS_EXPRESSION("as_expression"),
    ATTRIBUTE("attribute"),
    ATTRIBUTE_ARGUMENT("attribute_argument"),
    ATTRIBUTE_ARGUMENT_LIST("attribute_argument_list"),
    ATTRIBUTE_LIST("attribute_list"),
    ATTRIBUTE_TARGET_SPECIFIER("attribute_target_specifier"),
    AWAIT_EXPRESSION("await_expression"),
    BASE_LIST("base_list"),
    BINARY_EXPRESSION("binary_expression"),
    BLOCK("block"),
    BOOLEAN_LITERAL("boolean_literal"),
    BRACKETED_ARGUMENT_LIST("bracketed_argument_list"),
    BRACKETED_PARAMETER_LIST("bracketed_parameter_list"),
    BREAK_STATEMENT("break_statement"),
    CALLING_CONVENTION("calling_convention"),
    CAST_EXPRESSION("cast_expression"),
    CATCH_CLAUSE("catch_clause"),
    CATCH_DECLARATION("catch_declaration"),
    CATCH_FILTER_CLAUSE("catch_filter_clause"),
    CHARACTER_LITERAL("character_literal"),
    CHARACTER_LITERAL_CONTENT("character_literal_content"),
    CHECKED_EXPRESSION("checked_expression"),
    CHECKED_STATEMENT("checked_statement"),
    CLASS_DECLARATION("class_declaration"),
    COMMENT("comment"),
    COMPILATION_UNIT("compilation_unit"),
    CONDITIONAL_ACCESS_EXPRESSION("conditional_access_expression"),
    CONDITIONAL_EXPRESSION("conditional_expression"),
    CONSTANT_PATTERN("constant_pattern"),
    CONSTRUCTOR_CONSTRAINT("constructor_constraint"),
    CONSTRUCTOR_DECLARATION("constructor_declaration"),
    CONSTRUCTOR_INITIALIZER("constructor_initializer"),
    CONTINUE_STATEMENT("continue_statement"),
    CONVERSION_OPERATOR_DECLARATION("conversion_operator_declaration"),
    DECLARATION("declaration"),
    DECLARATION_EXPRESSION("declaration_expression"),
    DECLARATION_LIST("declaration_list"),
    DECLARATION_PATTERN("declaration_pattern"),
    DEFAULT_EXPRESSION("default_expression"),
    DELEGATE_DECLARATION("delegate_declaration"),
    DESTRUCTOR_DECLARATION("destructor_declaration"),
    DISCARD("discard"),
    DO_STATEMENT("do_statement"),
    ELEMENT_ACCESS_EXPRESSION("element_access_expression"),
    ELEMENT_BINDING_EXPRESSION("element_binding_expression"),
    EMPTY_STATEMENT("empty_statement"),
    ENUM_DECLARATION("enum_declaration"),
    ENUM_MEMBER_DECLARATION("enum_member_declaration"),
    ENUM_MEMBER_DECLARATION_LIST("enum_member_declaration_list"),
    ESCAPE_SEQUENCE("escape_sequence"),
    EVENT_DECLARATION("event_declaration"),
    EVENT_FIELD_DECLARATION("event_field_declaration"),
    EXPLICIT_INTERFACE_SPECIFIER("explicit_interface_specifier"),
    EXPRESSION("expression"),
    EXPRESSION_STATEMENT("expression_statement"),
    EXTERN_ALIAS_DIRECTIVE("extern_alias_directive"),
    FIELD_DECLARATION("field_declaration"),
    FILE_SCOPED_NAMESPACE_DECLARATION("file_scoped_namespace_declaration"),
    FINALLY_CLAUSE("finally_clause"),
    FIXED_STATEMENT("fixed_statement"),
    FOREACH_STATEMENT("foreach_statement"),
    FOR_STATEMENT("for_statement"),
    FROM_CLAUSE("from_clause"),
    FUNCTION_POINTER_PARAMETER("function_pointer_parameter"),
    FUNCTION_POINTER_TYPE("function_pointer_type"),
    GENERIC_NAME("generic_name"),
    GLOBAL_ATTRIBUTE("global_attribute"),
    GLOBAL_STATEMENT("global_statement"),
    GOTO_STATEMENT("goto_statement"),
    GROUP_CLAUSE("group_clause"),
    IDENTIFIER("identifier"),
    IF_STATEMENT("if_statement"),
    IMPLICIT_ARRAY_CREATION_EXPRESSION("implicit_array_creation_expression"),
    IMPLICIT_OBJECT_CREATION_EXPRESSION("implicit_object_creation_expression"),
    IMPLICIT_PARAMETER("implicit_parameter"),
    IMPLICIT_STACKALLOC_EXPRESSION("implicit_stackalloc_expression"),
    IMPLICIT_TYPE("implicit_type"),
    INDEXER_DECLARATION("indexer_declaration"),
    INITIALIZER_EXPRESSION("initializer_expression"),
    INTEGER_LITERAL("integer_literal"),
    INTERFACE_DECLARATION("interface_declaration"),
    INTERPOLATED_STRING_EXPRESSION("interpolated_string_expression"),
    INTERPOLATION("interpolation"),
    INTERPOLATION_ALIGNMENT_CLAUSE("interpolation_alignment_clause"),
    INTERPOLATION_BRACE("interpolation_brace"),
    INTERPOLATION_FORMAT_CLAUSE("interpolation_format_clause"),
    INTERPOLATION_QUOTE("interpolation_quote"),
    INTERPOLATION_START("interpolation_start"),
    INVOCATION_EXPRESSION("invocation_expression"),
    IS_EXPRESSION("is_expression"),
    IS_PATTERN_EXPRESSION("is_pattern_expression"),
    JOIN_CLAUSE("join_clause"),
    JOIN_INTO_CLAUSE("join_into_clause"),
    LABELED_STATEMENT("labeled_statement"),
    LAMBDA_EXPRESSION("lambda_expression"),
    LET_CLAUSE("let_clause"),
    LIST_PATTERN("list_pattern"),
    LITERAL("literal"),
    LOCAL_DECLARATION_STATEMENT("local_declaration_statement"),
    LOCAL_FUNCTION_STATEMENT("local_function_statement"),
    LOCK_STATEMENT("lock_statement"),
    LVALUE_EXPRESSION("lvalue_expression"),
    MAKEREF_EXPRESSION("makeref_expression"),
    MEMBER_ACCESS_EXPRESSION("member_access_expression"),
    MEMBER_BINDING_EXPRESSION("member_binding_expression"),
    METHOD_DECLARATION("method_declaration"),
    MODIFIER("modifier"),
    NAMESPACE_DECLARATION("namespace_declaration"),
    NEGATED_PATTERN("negated_pattern"),
    NON_LVALUE_EXPRESSION("non_lvalue_expression"),
    NULLABLE_TYPE("nullable_type"),
    NULL_LITERAL("null_literal"),
    OBJECT_CREATION_EXPRESSION("object_creation_expression"),
    OPERATOR_DECLARATION("operator_declaration"),
    ORDER_BY_CLAUSE("order_by_clause"),
    OR_PATTERN("or_pattern"),
    PARAMETER("parameter"),
    PARAMETER_LIST("parameter_list"),
    PARENTHESIZED_EXPRESSION("parenthesized_expression"),
    PARENTHESIZED_PATTERN("parenthesized_pattern"),
    PARENTHESIZED_VARIABLE_DESIGNATION("parenthesized_variable_designation"),
    PATTERN("pattern"),
    POINTER_TYPE("pointer_type"),
    POSITIONAL_PATTERN_CLAUSE("positional_pattern_clause"),
    POSTFIX_UNARY_EXPRESSION("postfix_unary_expression"),
    PREDEFINED_TYPE("predefined_type"),
    PREFIX_UNARY_EXPRESSION("prefix_unary_expression"),
    PREPROC_ARG("preproc_arg"),
    PREPROC_DEFINE("preproc_define"),
    PREPROC_ELIF("preproc_elif"),
    PREPROC_ELSE("preproc_else"),
    PREPROC_ENDREGION("preproc_endregion"),
    PREPROC_ERROR("preproc_error"),
    PREPROC_IF("preproc_if"),
    PREPROC_LINE("preproc_line"),
    PREPROC_NULLABLE("preproc_nullable"),
    PREPROC_PRAGMA("preproc_pragma"),
    PREPROC_REGION("preproc_region"),
    PREPROC_UNDEF("preproc_undef"),
    PREPROC_WARNING("preproc_warning"),
    PRIMARY_CONSTRUCTOR_BASE_TYPE("primary_constructor_base_type"),
    PROPERTY_DECLARATION("property_declaration"),
    PROPERTY_PATTERN_CLAUSE("property_pattern_clause"),
    QUALIFIED_NAME("qualified_name"),
    QUERY_EXPRESSION("query_expression"),
    RANGE_EXPRESSION("range_expression"),
    RAW_STRING_CONTENT("raw_string_content"),
    RAW_STRING_END("raw_string_end"),
    RAW_STRING_LITERAL("raw_string_literal"),
    RAW_STRING_START("raw_string_start"),
    REAL_LITERAL("real_literal"),
    RECORD_DECLARATION("record_declaration"),
    RECURSIVE_PATTERN("recursive_pattern"),
    REFTYPE_EXPRESSION("reftype_expression"),
    REFVALUE_EXPRESSION("refvalue_expression"),
    REF_EXPRESSION("ref_expression"),
    REF_TYPE("ref_type"),
    RELATIONAL_PATTERN("relational_pattern"),
    RETURN_STATEMENT("return_statement"),
    SCOPED_TYPE("scoped_type"),
    SELECT_CLAUSE("select_clause"),
    SHEBANG_DIRECTIVE("shebang_directive"),
    SIZEOF_EXPRESSION("sizeof_expression"),
    STACKALLOC_EXPRESSION("stackalloc_expression"),
    STATEMENT("statement"),
    STRING_CONTENT("string_content"),
    STRING_LITERAL("string_literal"),
    STRING_LITERAL_CONTENT("string_literal_content"),
    STRING_LITERAL_ENCODING("string_literal_encoding"),
    STRUCT_DECLARATION("struct_declaration"),
    SUBPATTERN("subpattern"),
    SWITCH_BODY("switch_body"),
    SWITCH_EXPRESSION("switch_expression"),
    SWITCH_EXPRESSION_ARM("switch_expression_arm"),
    SWITCH_SECTION("switch_section"),
    SWITCH_STATEMENT("switch_statement"),
    THROW_EXPRESSION("throw_expression"),
    THROW_STATEMENT("throw_statement"),
    TRY_STATEMENT("try_statement"),
    TUPLE_ELEMENT("tuple_element"),
    TUPLE_EXPRESSION("tuple_expression"),
    TUPLE_PATTERN("tuple_pattern"),
    TUPLE_TYPE("tuple_type"),
    TYPE("type"),
    TYPEOF_EXPRESSION("typeof_expression"),
    TYPE_ARGUMENT_LIST("type_argument_list"),
    TYPE_DECLARATION("type_declaration"),
    TYPE_PARAMETER("type_parameter"),
    TYPE_PARAMETER_CONSTRAINT("type_parameter_constraint"),
    TYPE_PARAMETER_CONSTRAINTS_CLAUSE("type_parameter_constraints_clause"),
    TYPE_PARAMETER_LIST("type_parameter_list"),
    TYPE_PATTERN("type_pattern"),
    UNARY_EXPRESSION("unary_expression"),
    UNSAFE_STATEMENT("unsafe_statement"),
    USING_DIRECTIVE("using_directive"),
    USING_STATEMENT("using_statement"),
    VARIABLE_DECLARATION("variable_declaration"),
    VARIABLE_DECLARATOR("variable_declarator"),
    VAR_PATTERN("var_pattern"),
    VERBATIM_STRING_LITERAL("verbatim_string_literal"),
    WHEN_CLAUSE("when_clause"),
    WHERE_CLAUSE("where_clause"),
    WHILE_STATEMENT("while_statement"),
    WITH_EXPRESSION("with_expression"),
    WITH_INITIALIZER("with_initializer"),
    YIELD_STATEMENT("yield_statement");

    public static final Set<CSharpNodeType> DECLARATION_SET = Set.of(
            CLASS_DECLARATION,
            CONSTRUCTOR_DECLARATION,
            CONVERSION_OPERATOR_DECLARATION,
            DELEGATE_DECLARATION,
            DESTRUCTOR_DECLARATION,
            ENUM_DECLARATION,
            EVENT_DECLARATION,
            EVENT_FIELD_DECLARATION,
            FIELD_DECLARATION,
            INDEXER_DECLARATION,
            INTERFACE_DECLARATION,
            METHOD_DECLARATION,
            NAMESPACE_DECLARATION,
            OPERATOR_DECLARATION,
            PREPROC_IF,
            PROPERTY_DECLARATION,
            RECORD_DECLARATION,
            STRUCT_DECLARATION,
            USING_DIRECTIVE);
    public static final Set<CSharpNodeType> EXPRESSION_SET = Set.of(LVALUE_EXPRESSION, NON_LVALUE_EXPRESSION);
    public static final Set<CSharpNodeType> LITERAL_SET = Set.of(
            BOOLEAN_LITERAL,
            CHARACTER_LITERAL,
            INTEGER_LITERAL,
            NULL_LITERAL,
            RAW_STRING_LITERAL,
            REAL_LITERAL,
            STRING_LITERAL,
            VERBATIM_STRING_LITERAL);
    public static final Set<CSharpNodeType> LVALUE_EXPRESSION_SET = Set.of(
            ELEMENT_ACCESS_EXPRESSION,
            ELEMENT_BINDING_EXPRESSION,
            GENERIC_NAME,
            IDENTIFIER,
            MEMBER_ACCESS_EXPRESSION,
            PARENTHESIZED_EXPRESSION,
            PREFIX_UNARY_EXPRESSION,
            TUPLE_EXPRESSION);
    public static final Set<CSharpNodeType> NON_LVALUE_EXPRESSION_SET = Set.of(
            ANONYMOUS_METHOD_EXPRESSION,
            ANONYMOUS_OBJECT_CREATION_EXPRESSION,
            ARRAY_CREATION_EXPRESSION,
            ASSIGNMENT_EXPRESSION,
            AS_EXPRESSION,
            AWAIT_EXPRESSION,
            BINARY_EXPRESSION,
            CAST_EXPRESSION,
            CHECKED_EXPRESSION,
            CONDITIONAL_ACCESS_EXPRESSION,
            CONDITIONAL_EXPRESSION,
            DEFAULT_EXPRESSION,
            IMPLICIT_ARRAY_CREATION_EXPRESSION,
            IMPLICIT_OBJECT_CREATION_EXPRESSION,
            IMPLICIT_STACKALLOC_EXPRESSION,
            INITIALIZER_EXPRESSION,
            INTERPOLATED_STRING_EXPRESSION,
            INVOCATION_EXPRESSION,
            IS_EXPRESSION,
            IS_PATTERN_EXPRESSION,
            LAMBDA_EXPRESSION,
            LITERAL,
            MAKEREF_EXPRESSION,
            OBJECT_CREATION_EXPRESSION,
            PARENTHESIZED_EXPRESSION,
            POSTFIX_UNARY_EXPRESSION,
            PREFIX_UNARY_EXPRESSION,
            PREPROC_IF,
            QUERY_EXPRESSION,
            RANGE_EXPRESSION,
            REFTYPE_EXPRESSION,
            REFVALUE_EXPRESSION,
            REF_EXPRESSION,
            SIZEOF_EXPRESSION,
            STACKALLOC_EXPRESSION,
            SWITCH_EXPRESSION,
            THROW_EXPRESSION,
            TYPEOF_EXPRESSION,
            WITH_EXPRESSION);
    public static final Set<CSharpNodeType> PATTERN_SET = Set.of(
            AND_PATTERN,
            CONSTANT_PATTERN,
            DECLARATION_PATTERN,
            DISCARD,
            LIST_PATTERN,
            NEGATED_PATTERN,
            OR_PATTERN,
            PARENTHESIZED_PATTERN,
            RECURSIVE_PATTERN,
            RELATIONAL_PATTERN,
            TYPE_PATTERN,
            VAR_PATTERN);
    public static final Set<CSharpNodeType> STATEMENT_SET = Set.of(
            BLOCK,
            BREAK_STATEMENT,
            CHECKED_STATEMENT,
            CONTINUE_STATEMENT,
            DO_STATEMENT,
            EMPTY_STATEMENT,
            EXPRESSION_STATEMENT,
            FIXED_STATEMENT,
            FOREACH_STATEMENT,
            FOR_STATEMENT,
            GOTO_STATEMENT,
            IF_STATEMENT,
            LABELED_STATEMENT,
            LOCAL_DECLARATION_STATEMENT,
            LOCAL_FUNCTION_STATEMENT,
            LOCK_STATEMENT,
            PREPROC_IF,
            RETURN_STATEMENT,
            SWITCH_STATEMENT,
            THROW_STATEMENT,
            TRY_STATEMENT,
            UNSAFE_STATEMENT,
            USING_STATEMENT,
            WHILE_STATEMENT,
            YIELD_STATEMENT);
    public static final Set<CSharpNodeType> TYPE_DECLARATION_SET = Set.of(
            CLASS_DECLARATION,
            DELEGATE_DECLARATION,
            ENUM_DECLARATION,
            INTERFACE_DECLARATION,
            RECORD_DECLARATION,
            STRUCT_DECLARATION);
    public static final Set<CSharpNodeType> TYPE_SET = Set.of(
            ALIAS_QUALIFIED_NAME,
            ARRAY_TYPE,
            FUNCTION_POINTER_TYPE,
            GENERIC_NAME,
            IDENTIFIER,
            IMPLICIT_TYPE,
            NULLABLE_TYPE,
            POINTER_TYPE,
            PREDEFINED_TYPE,
            QUALIFIED_NAME,
            REF_TYPE,
            SCOPED_TYPE,
            TUPLE_TYPE);

    private final @Nullable String type;

    CSharpNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static CSharpNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static CSharpNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        CSharpNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, CSharpNodeType> LOOKUP = initLookup();

    private static Map<String, CSharpNodeType> initLookup() {
        HashMap<String, CSharpNodeType> m = new HashMap<>();
        for (CSharpNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
