package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code haskell} from tree-sitter {@code node-types.json}.
 */
public enum HaskellNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ABSTRACT_FAMILY("abstract_family"),
    ALL_NAMES("all_names"),
    ALTERNATIVE("alternative"),
    ALTERNATIVES("alternatives"),
    ANNOTATED("annotated"),
    APPLY("apply"),
    ARITHMETIC_SEQUENCE("arithmetic_sequence"),
    AS("as"),
    ASSOCIATED_TYPE("associated_type"),
    BIND("bind"),
    BINDING_LIST("binding_list"),
    BOOLEAN_("boolean"),
    CALLING_CONVENTION("calling_convention"),
    CASE_("case"),
    CHAR_("char"),
    CHILDREN("children"),
    CLASS_("class"),
    CLASS_DECL("class_decl"),
    CLASS_DECLARATIONS("class_declarations"),
    COMMENT("comment"),
    CONDITIONAL("conditional"),
    CONSTRAINT("constraint"),
    CONSTRAINTS("constraints"),
    CONSTRUCTOR("constructor"),
    CONSTRUCTOR_OPERATOR("constructor_operator"),
    CONSTRUCTOR_SYNONYM("constructor_synonym"),
    CONSTRUCTOR_SYNONYMS("constructor_synonyms"),
    CONTEXT("context"),
    CPP("cpp"),
    DATA_CONSTRUCTOR("data_constructor"),
    DATA_CONSTRUCTORS("data_constructors"),
    DATA_FAMILY("data_family"),
    DATA_INSTANCE("data_instance"),
    DATA_TYPE("data_type"),
    DECL("decl"),
    DECLARATION("declaration"),
    DECLARATIONS("declarations"),
    DEFAULT_SIGNATURE("default_signature"),
    DEFAULT_TYPES("default_types"),
    DERIVING("deriving"),
    DERIVING_INSTANCE("deriving_instance"),
    DERIVING_STRATEGY("deriving_strategy"),
    DO_("do"),
    DO_MODULE("do_module"),
    EMPTY_LIST("empty_list"),
    ENTITY("entity"),
    EQUATION("equation"),
    EQUATIONS("equations"),
    EXP("exp"),
    EXPLICIT_TYPE("explicit_type"),
    EXPORT("export"),
    EXPORTS("exports"),
    EXPRESSION("expression"),
    FIELD("field"),
    FIELDS("fields"),
    FIELD_NAME("field_name"),
    FIELD_PATH("field_path"),
    FIELD_PATTERN("field_pattern"),
    FIELD_UPDATE("field_update"),
    FIXITY("fixity"),
    FLOAT_("float"),
    FORALL("forall"),
    FORALL_REQUIRED("forall_required"),
    FOREIGN_EXPORT("foreign_export"),
    FOREIGN_IMPORT("foreign_import"),
    FUNCTION("function"),
    FUNCTION_HEAD_PARENS("function_head_parens"),
    FUNDEP("fundep"),
    FUNDEPS("fundeps"),
    GADT_CONSTRUCTOR("gadt_constructor"),
    GADT_CONSTRUCTORS("gadt_constructors"),
    GENERATOR("generator"),
    GROUP("group"),
    GUARD("guard"),
    GUARDS("guards"),
    HADDOCK("haddock"),
    HASKELL("haskell"),
    HEADER("header"),
    IMPLICIT_PARAMETER("implicit_parameter"),
    IMPLICIT_VARIABLE("implicit_variable"),
    IMPORTS("imports"),
    IMPORT_("import"),
    IMPORT_LIST("import_list"),
    IMPORT_NAME("import_name"),
    IMPORT_PACKAGE("import_package"),
    INFERRED("inferred"),
    INFIX("infix"),
    INFIX_ID("infix_id"),
    INSTANCE("instance"),
    INSTANCE_DECL("instance_decl"),
    INSTANCE_DECLARATIONS("instance_declarations"),
    INTEGER("integer"),
    INVISIBLE("invisible"),
    IRREFUTABLE("irrefutable"),
    KIND_APPLICATION("kind_application"),
    KIND_SIGNATURE("kind_signature"),
    LABEL("label"),
    LAMBDA("lambda"),
    LAMBDA_CASE("lambda_case"),
    LAMBDA_CASES("lambda_cases"),
    LAZY_FIELD("lazy_field"),
    LEFT_SECTION("left_section"),
    LET("let"),
    LET_IN("let_in"),
    LINEAR_FUNCTION("linear_function"),
    LIST("list"),
    LIST_COMPREHENSION("list_comprehension"),
    LITERAL("literal"),
    LOCAL_BINDS("local_binds"),
    MATCH("match"),
    MODIFIER("modifier"),
    MODULE("module"),
    MODULE_EXPORT("module_export"),
    MODULE_ID("module_id"),
    MULTI_WAY_IF("multi_way_if"),
    NAME("name"),
    NAMESPACE("namespace"),
    NEGATION("negation"),
    NEWTYPE("newtype"),
    NEWTYPE_CONSTRUCTOR("newtype_constructor"),
    OPERATOR("operator"),
    PARENS("parens"),
    PATTERN("pattern"),
    PATTERNS("patterns"),
    PATTERN_GUARD("pattern_guard"),
    PATTERN_SYNONYM("pattern_synonym"),
    PRAGMA("pragma"),
    PREFIX("prefix"),
    PREFIX_ID("prefix_id"),
    PREFIX_LIST("prefix_list"),
    PREFIX_TUPLE("prefix_tuple"),
    PREFIX_UNBOXED_SUM("prefix_unboxed_sum"),
    PREFIX_UNBOXED_TUPLE("prefix_unboxed_tuple"),
    PROJECTION("projection"),
    PROJECTION_SELECTOR("projection_selector"),
    PROMOTED("promoted"),
    QUALIFIED("qualified"),
    QUALIFIER("qualifier"),
    QUALIFIERS("qualifiers"),
    QUANTIFIED_TYPE("quantified_type"),
    QUANTIFIED_VARIABLES("quantified_variables"),
    QUASIQUOTE("quasiquote"),
    QUASIQUOTE_BODY("quasiquote_body"),
    QUOTE("quote"),
    QUOTED_DECLS("quoted_decls"),
    QUOTED_EXPRESSION("quoted_expression"),
    QUOTED_PATTERN("quoted_pattern"),
    QUOTED_TYPE("quoted_type"),
    QUOTER("quoter"),
    REC("rec"),
    RECORD_("record"),
    RIGHT_SECTION("right_section"),
    ROLE_ANNOTATION("role_annotation"),
    SAFETY("safety"),
    SIGNATURE("signature"),
    SPECIAL("special"),
    SPLICE("splice"),
    STAR("star"),
    STATEMENT("statement"),
    STRICT("strict"),
    STRICT_FIELD("strict_field"),
    STRING("string"),
    TH_QUOTED_NAME("th_quoted_name"),
    TOP_SPLICE("top_splice"),
    TRANSFORM("transform"),
    TUPLE("tuple"),
    TYPE("type"),
    TYPED_QUOTE("typed_quote"),
    TYPE_APPLICATION("type_application"),
    TYPE_BINDER("type_binder"),
    TYPE_FAMILY("type_family"),
    TYPE_FAMILY_INJECTIVITY("type_family_injectivity"),
    TYPE_FAMILY_RESULT("type_family_result"),
    TYPE_INSTANCE("type_instance"),
    TYPE_PARAM("type_param"),
    TYPE_PARAMS("type_params"),
    TYPE_PATTERNS("type_patterns"),
    TYPE_ROLE("type_role"),
    TYPE_SYNOMYM("type_synomym"),
    UNBOXED_SUM("unboxed_sum"),
    UNBOXED_TUPLE("unboxed_tuple"),
    UNBOXED_UNIT("unboxed_unit"),
    UNIT("unit"),
    VARIABLE("variable"),
    VIA("via"),
    VIEW_PATTERN("view_pattern"),
    WILDCARD("wildcard");

    public static final Set<HaskellNodeType> CLASS_DECL_SET =
            Set.of(DATA_FAMILY, DECL, DEFAULT_SIGNATURE, FIXITY, TYPE_FAMILY, TYPE_INSTANCE);
    public static final Set<HaskellNodeType> CONSTRAINTS_SET =
            Set.of(CONSTRAINT, CONTEXT, FORALL, IMPLICIT_PARAMETER, SIGNATURE);
    public static final Set<HaskellNodeType> CONSTRAINT_SET = Set.of(
            APPLY,
            INFIX,
            LITERAL,
            NAME,
            PARENS,
            PREFIX_ID,
            PREFIX_TUPLE,
            PREFIX_UNBOXED_SUM,
            PREFIX_UNBOXED_TUPLE,
            PROMOTED,
            QUALIFIED,
            QUASIQUOTE,
            SPLICE,
            TUPLE,
            UNBOXED_UNIT,
            UNIT,
            VARIABLE,
            WILDCARD);
    public static final Set<HaskellNodeType> DECLARATION_SET = Set.of(
            CLASS_,
            DATA_FAMILY,
            DATA_INSTANCE,
            DATA_TYPE,
            DECL,
            DEFAULT_TYPES,
            DERIVING_INSTANCE,
            FIXITY,
            FOREIGN_EXPORT,
            FOREIGN_IMPORT,
            INSTANCE,
            KIND_SIGNATURE,
            NEWTYPE,
            PATTERN_SYNONYM,
            ROLE_ANNOTATION,
            TOP_SPLICE,
            TYPE_FAMILY,
            TYPE_INSTANCE,
            TYPE_SYNOMYM);
    public static final Set<HaskellNodeType> DECL_SET = Set.of(BIND, FUNCTION, SIGNATURE);
    public static final Set<HaskellNodeType> EXPRESSION_SET = Set.of(
            APPLY,
            ARITHMETIC_SEQUENCE,
            CASE_,
            CONDITIONAL,
            CONSTRUCTOR,
            DO_,
            IMPLICIT_VARIABLE,
            INFIX,
            LABEL,
            LAMBDA,
            LAMBDA_CASE,
            LAMBDA_CASES,
            LEFT_SECTION,
            LET_IN,
            LIST,
            LIST_COMPREHENSION,
            LITERAL,
            MULTI_WAY_IF,
            NEGATION,
            PARENS,
            PREFIX_ID,
            PREFIX_TUPLE,
            PREFIX_UNBOXED_SUM,
            PREFIX_UNBOXED_TUPLE,
            PROJECTION,
            PROJECTION_SELECTOR,
            QUALIFIED,
            QUASIQUOTE,
            QUOTE,
            RECORD_,
            RIGHT_SECTION,
            SPLICE,
            TH_QUOTED_NAME,
            TUPLE,
            TYPED_QUOTE,
            UNBOXED_SUM,
            UNBOXED_TUPLE,
            UNBOXED_UNIT,
            UNIT,
            VARIABLE);
    public static final Set<HaskellNodeType> GUARD_SET = Set.of(BOOLEAN_, LET, PATTERN_GUARD);
    public static final Set<HaskellNodeType> INSTANCE_DECL_SET = Set.of(DATA_INSTANCE, DECL, TYPE_INSTANCE);
    public static final Set<HaskellNodeType> PATTERN_SET = Set.of(
            APPLY,
            AS,
            CONSTRUCTOR,
            INFIX,
            IRREFUTABLE,
            LIST,
            LITERAL,
            NEGATION,
            PARENS,
            PREFIX_ID,
            PREFIX_TUPLE,
            PREFIX_UNBOXED_SUM,
            PREFIX_UNBOXED_TUPLE,
            QUALIFIED,
            QUASIQUOTE,
            RECORD_,
            SPLICE,
            STRICT,
            TUPLE,
            UNBOXED_SUM,
            UNBOXED_TUPLE,
            UNBOXED_UNIT,
            UNIT,
            VARIABLE,
            WILDCARD);
    public static final Set<HaskellNodeType> QUALIFIER_SET = Set.of(BOOLEAN_, GENERATOR, GROUP, LET, TRANSFORM);
    public static final Set<HaskellNodeType> QUANTIFIED_TYPE_SET =
            Set.of(CONTEXT, FORALL, FORALL_REQUIRED, FUNCTION, IMPLICIT_PARAMETER, LINEAR_FUNCTION, TYPE);
    public static final Set<HaskellNodeType> STATEMENT_SET = Set.of(BIND, EXP, LET, REC);
    public static final Set<HaskellNodeType> TYPE_PARAM_SET = Set.of(INVISIBLE, PARENS, VARIABLE, WILDCARD);
    public static final Set<HaskellNodeType> TYPE_SET = Set.of(
            APPLY,
            INFIX,
            LIST,
            LITERAL,
            NAME,
            PARENS,
            PREFIX_ID,
            PREFIX_LIST,
            PREFIX_TUPLE,
            PREFIX_UNBOXED_SUM,
            PREFIX_UNBOXED_TUPLE,
            PROMOTED,
            QUALIFIED,
            QUASIQUOTE,
            SPLICE,
            STAR,
            TUPLE,
            UNBOXED_SUM,
            UNBOXED_TUPLE,
            UNBOXED_UNIT,
            UNIT,
            VARIABLE,
            WILDCARD);

    private final @Nullable String type;

    HaskellNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static HaskellNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static HaskellNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        HaskellNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, HaskellNodeType> LOOKUP = initLookup();

    private static Map<String, HaskellNodeType> initLookup() {
        HashMap<String, HaskellNodeType> m = new HashMap<>();
        for (HaskellNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
