package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code typescript} from tree-sitter {@code node-types.json}.
 */
public enum TypescriptNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ABSTRACT_CLASS_DECLARATION("abstract_class_declaration"),
    ABSTRACT_METHOD_SIGNATURE("abstract_method_signature"),
    ACCESSIBILITY_MODIFIER("accessibility_modifier"),
    ADDING_TYPE_ANNOTATION("adding_type_annotation"),
    AMBIENT_DECLARATION("ambient_declaration"),
    ARGUMENTS("arguments"),
    ARRAY("array"),
    ARRAY_PATTERN("array_pattern"),
    ARRAY_TYPE("array_type"),
    ARROW_FUNCTION("arrow_function"),
    ASSERTS("asserts"),
    ASSERTS_ANNOTATION("asserts_annotation"),
    ASSIGNMENT_EXPRESSION("assignment_expression"),
    ASSIGNMENT_PATTERN("assignment_pattern"),
    AS_EXPRESSION("as_expression"),
    AUGMENTED_ASSIGNMENT_EXPRESSION("augmented_assignment_expression"),
    AWAIT_EXPRESSION("await_expression"),
    BINARY_EXPRESSION("binary_expression"),
    BREAK_STATEMENT("break_statement"),
    CALL_EXPRESSION("call_expression"),
    CALL_SIGNATURE("call_signature"),
    CATCH_CLAUSE("catch_clause"),
    CLASS_("class"),
    CLASS_BODY("class_body"),
    CLASS_DECLARATION("class_declaration"),
    CLASS_HERITAGE("class_heritage"),
    CLASS_STATIC_BLOCK("class_static_block"),
    COMMENT("comment"),
    COMPUTED_PROPERTY_NAME("computed_property_name"),
    CONDITIONAL_TYPE("conditional_type"),
    CONSTRAINT("constraint"),
    CONSTRUCTOR_TYPE("constructor_type"),
    CONSTRUCT_SIGNATURE("construct_signature"),
    CONTINUE_STATEMENT("continue_statement"),
    DEBUGGER_STATEMENT("debugger_statement"),
    DECLARATION("declaration"),
    DECORATOR("decorator"),
    DEFAULT_TYPE("default_type"),
    DO_STATEMENT("do_statement"),
    ELSE_CLAUSE("else_clause"),
    EMPTY_STATEMENT("empty_statement"),
    ENUM_ASSIGNMENT("enum_assignment"),
    ENUM_BODY("enum_body"),
    ENUM_DECLARATION("enum_declaration"),
    ESCAPE_SEQUENCE("escape_sequence"),
    EXISTENTIAL_TYPE("existential_type"),
    EXPORT_CLAUSE("export_clause"),
    EXPORT_SPECIFIER("export_specifier"),
    EXPORT_STATEMENT("export_statement"),
    EXPRESSION("expression"),
    EXPRESSION_STATEMENT("expression_statement"),
    EXTENDS_CLAUSE("extends_clause"),
    EXTENDS_TYPE_CLAUSE("extends_type_clause"),
    FALSE("false"),
    FINALLY_CLAUSE("finally_clause"),
    FLOW_MAYBE_TYPE("flow_maybe_type"),
    FORMAL_PARAMETERS("formal_parameters"),
    FOR_IN_STATEMENT("for_in_statement"),
    FOR_STATEMENT("for_statement"),
    FUNCTION_DECLARATION("function_declaration"),
    FUNCTION_EXPRESSION("function_expression"),
    FUNCTION_SIGNATURE("function_signature"),
    FUNCTION_TYPE("function_type"),
    GENERATOR_FUNCTION("generator_function"),
    GENERATOR_FUNCTION_DECLARATION("generator_function_declaration"),
    GENERIC_TYPE("generic_type"),
    HASH_BANG_LINE("hash_bang_line"),
    HTML_COMMENT("html_comment"),
    IDENTIFIER("identifier"),
    IF_STATEMENT("if_statement"),
    IMPLEMENTS_CLAUSE("implements_clause"),
    IMPORT_("import"),
    IMPORT_ALIAS("import_alias"),
    IMPORT_ATTRIBUTE("import_attribute"),
    IMPORT_CLAUSE("import_clause"),
    IMPORT_REQUIRE_CLAUSE("import_require_clause"),
    IMPORT_SPECIFIER("import_specifier"),
    IMPORT_STATEMENT("import_statement"),
    INDEX_SIGNATURE("index_signature"),
    INDEX_TYPE_QUERY("index_type_query"),
    INFER_TYPE("infer_type"),
    INSTANTIATION_EXPRESSION("instantiation_expression"),
    INTERFACE_BODY("interface_body"),
    INTERFACE_DECLARATION("interface_declaration"),
    INTERNAL_MODULE("internal_module"),
    INTERSECTION_TYPE("intersection_type"),
    LABELED_STATEMENT("labeled_statement"),
    LEXICAL_DECLARATION("lexical_declaration"),
    LITERAL_TYPE("literal_type"),
    LOOKUP_TYPE("lookup_type"),
    MAPPED_TYPE_CLAUSE("mapped_type_clause"),
    MEMBER_EXPRESSION("member_expression"),
    META_PROPERTY("meta_property"),
    METHOD_DEFINITION("method_definition"),
    METHOD_SIGNATURE("method_signature"),
    MODULE("module"),
    NAMED_IMPORTS("named_imports"),
    NAMESPACE_EXPORT("namespace_export"),
    NAMESPACE_IMPORT("namespace_import"),
    NESTED_IDENTIFIER("nested_identifier"),
    NESTED_TYPE_IDENTIFIER("nested_type_identifier"),
    NEW_EXPRESSION("new_expression"),
    NON_NULL_EXPRESSION("non_null_expression"),
    NULL("null"),
    NUMBER("number"),
    OBJECT("object"),
    OBJECT_ASSIGNMENT_PATTERN("object_assignment_pattern"),
    OBJECT_PATTERN("object_pattern"),
    OBJECT_TYPE("object_type"),
    OMITTING_TYPE_ANNOTATION("omitting_type_annotation"),
    OPTING_TYPE_ANNOTATION("opting_type_annotation"),
    OPTIONAL_CHAIN("optional_chain"),
    OPTIONAL_PARAMETER("optional_parameter"),
    OPTIONAL_TYPE("optional_type"),
    OVERRIDE_MODIFIER("override_modifier"),
    PAIR("pair"),
    PAIR_PATTERN("pair_pattern"),
    PARENTHESIZED_EXPRESSION("parenthesized_expression"),
    PARENTHESIZED_TYPE("parenthesized_type"),
    PATTERN("pattern"),
    PREDEFINED_TYPE("predefined_type"),
    PRIMARY_EXPRESSION("primary_expression"),
    PRIMARY_TYPE("primary_type"),
    PRIVATE_PROPERTY_IDENTIFIER("private_property_identifier"),
    PROGRAM("program"),
    PROPERTY_IDENTIFIER("property_identifier"),
    PROPERTY_SIGNATURE("property_signature"),
    PUBLIC_FIELD_DEFINITION("public_field_definition"),
    READONLY_TYPE("readonly_type"),
    REGEX("regex"),
    REGEX_FLAGS("regex_flags"),
    REGEX_PATTERN("regex_pattern"),
    REQUIRED_PARAMETER("required_parameter"),
    REST_PATTERN("rest_pattern"),
    REST_TYPE("rest_type"),
    RETURN_STATEMENT("return_statement"),
    SATISFIES_EXPRESSION("satisfies_expression"),
    SEQUENCE_EXPRESSION("sequence_expression"),
    SHORTHAND_PROPERTY_IDENTIFIER("shorthand_property_identifier"),
    SHORTHAND_PROPERTY_IDENTIFIER_PATTERN("shorthand_property_identifier_pattern"),
    SPREAD_ELEMENT("spread_element"),
    STATEMENT("statement"),
    STATEMENT_BLOCK("statement_block"),
    STATEMENT_IDENTIFIER("statement_identifier"),
    STRING("string"),
    STRING_FRAGMENT("string_fragment"),
    SUBSCRIPT_EXPRESSION("subscript_expression"),
    SUPER_("super"),
    SWITCH_BODY("switch_body"),
    SWITCH_CASE("switch_case"),
    SWITCH_DEFAULT("switch_default"),
    SWITCH_STATEMENT("switch_statement"),
    TEMPLATE_LITERAL_TYPE("template_literal_type"),
    TEMPLATE_STRING("template_string"),
    TEMPLATE_SUBSTITUTION("template_substitution"),
    TEMPLATE_TYPE("template_type"),
    TERNARY_EXPRESSION("ternary_expression"),
    THIS_("this"),
    THIS_TYPE("this_type"),
    THROW_STATEMENT("throw_statement"),
    TRUE("true"),
    TRY_STATEMENT("try_statement"),
    TUPLE_TYPE("tuple_type"),
    TYPE("type"),
    TYPE_ALIAS_DECLARATION("type_alias_declaration"),
    TYPE_ANNOTATION("type_annotation"),
    TYPE_ARGUMENTS("type_arguments"),
    TYPE_ASSERTION("type_assertion"),
    TYPE_IDENTIFIER("type_identifier"),
    TYPE_PARAMETER("type_parameter"),
    TYPE_PARAMETERS("type_parameters"),
    TYPE_PREDICATE("type_predicate"),
    TYPE_PREDICATE_ANNOTATION("type_predicate_annotation"),
    TYPE_QUERY("type_query"),
    UNARY_EXPRESSION("unary_expression"),
    UNDEFINED("undefined"),
    UNION_TYPE("union_type"),
    UPDATE_EXPRESSION("update_expression"),
    VARIABLE_DECLARATION("variable_declaration"),
    VARIABLE_DECLARATOR("variable_declarator"),
    WHILE_STATEMENT("while_statement"),
    WITH_STATEMENT("with_statement"),
    YIELD_EXPRESSION("yield_expression");

    public static final Set<TypescriptNodeType> DECLARATION_SET = Set.of(
            ABSTRACT_CLASS_DECLARATION,
            AMBIENT_DECLARATION,
            CLASS_DECLARATION,
            ENUM_DECLARATION,
            FUNCTION_DECLARATION,
            FUNCTION_SIGNATURE,
            GENERATOR_FUNCTION_DECLARATION,
            IMPORT_ALIAS,
            INTERFACE_DECLARATION,
            INTERNAL_MODULE,
            LEXICAL_DECLARATION,
            MODULE,
            TYPE_ALIAS_DECLARATION,
            VARIABLE_DECLARATION);
    public static final Set<TypescriptNodeType> EXPRESSION_SET = Set.of(
            ASSIGNMENT_EXPRESSION,
            AS_EXPRESSION,
            AUGMENTED_ASSIGNMENT_EXPRESSION,
            AWAIT_EXPRESSION,
            BINARY_EXPRESSION,
            INSTANTIATION_EXPRESSION,
            INTERNAL_MODULE,
            NEW_EXPRESSION,
            PRIMARY_EXPRESSION,
            SATISFIES_EXPRESSION,
            TERNARY_EXPRESSION,
            TYPE_ASSERTION,
            UNARY_EXPRESSION,
            UPDATE_EXPRESSION,
            YIELD_EXPRESSION);
    public static final Set<TypescriptNodeType> PATTERN_SET = Set.of(
            ARRAY_PATTERN,
            IDENTIFIER,
            MEMBER_EXPRESSION,
            NON_NULL_EXPRESSION,
            OBJECT_PATTERN,
            REST_PATTERN,
            SUBSCRIPT_EXPRESSION,
            UNDEFINED);
    public static final Set<TypescriptNodeType> PRIMARY_EXPRESSION_SET = Set.of(
            ARRAY,
            ARROW_FUNCTION,
            CALL_EXPRESSION,
            CLASS_,
            FALSE,
            FUNCTION_EXPRESSION,
            GENERATOR_FUNCTION,
            IDENTIFIER,
            MEMBER_EXPRESSION,
            META_PROPERTY,
            NON_NULL_EXPRESSION,
            NULL,
            NUMBER,
            OBJECT,
            PARENTHESIZED_EXPRESSION,
            REGEX,
            STRING,
            SUBSCRIPT_EXPRESSION,
            SUPER_,
            TEMPLATE_STRING,
            THIS_,
            TRUE,
            UNDEFINED);
    public static final Set<TypescriptNodeType> PRIMARY_TYPE_SET = Set.of(
            ARRAY_TYPE,
            CONDITIONAL_TYPE,
            EXISTENTIAL_TYPE,
            FLOW_MAYBE_TYPE,
            GENERIC_TYPE,
            INDEX_TYPE_QUERY,
            INTERSECTION_TYPE,
            LITERAL_TYPE,
            LOOKUP_TYPE,
            NESTED_TYPE_IDENTIFIER,
            OBJECT_TYPE,
            PARENTHESIZED_TYPE,
            PREDEFINED_TYPE,
            TEMPLATE_LITERAL_TYPE,
            THIS_TYPE,
            TUPLE_TYPE,
            TYPE_IDENTIFIER,
            TYPE_QUERY,
            UNION_TYPE);
    public static final Set<TypescriptNodeType> STATEMENT_SET = Set.of(
            BREAK_STATEMENT,
            CONTINUE_STATEMENT,
            DEBUGGER_STATEMENT,
            DECLARATION,
            DO_STATEMENT,
            EMPTY_STATEMENT,
            EXPORT_STATEMENT,
            EXPRESSION_STATEMENT,
            FOR_IN_STATEMENT,
            FOR_STATEMENT,
            IF_STATEMENT,
            IMPORT_STATEMENT,
            LABELED_STATEMENT,
            RETURN_STATEMENT,
            STATEMENT_BLOCK,
            SWITCH_STATEMENT,
            THROW_STATEMENT,
            TRY_STATEMENT,
            WHILE_STATEMENT,
            WITH_STATEMENT);
    public static final Set<TypescriptNodeType> TYPE_SET = Set.of(
            CALL_EXPRESSION,
            CONSTRUCTOR_TYPE,
            FUNCTION_TYPE,
            INFER_TYPE,
            MEMBER_EXPRESSION,
            PRIMARY_TYPE,
            READONLY_TYPE);

    private final @Nullable String type;

    TypescriptNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static TypescriptNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static TypescriptNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        TypescriptNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, TypescriptNodeType> LOOKUP = initLookup();

    private static Map<String, TypescriptNodeType> initLookup() {
        HashMap<String, TypescriptNodeType> m = new HashMap<>();
        for (TypescriptNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
