
tasks.named('downloadSource') {
    url = "https://github.com/dlvandenberg/tree-sitter-angular/archive/refs/tags/v${upstreamVersion}.zip"
}

tasks.named("buildNative") {
    def newSrcDir = downloadDir.dir("tree-sitter-angular-${upstreamVersion}/src")
    additionalCFiles = newSrcDir.asFileTree.matching {
        include("**/*.c")
    }
    additionalIncludeDirs = project.files(newSrcDir)
}
