package org.treesitter;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.jspecify.annotations.Nullable;

/**
 * Node types for {@code ocaml} from tree-sitter {@code node-types.json}.
 */
public enum OcamlNodeType {
    /** Represents a null TSNode reference or a TSNode with a null type. */
    __NULL__(null),
    ABSTRACT_TYPE("abstract_type"),
    ADD_OPERATOR("add_operator"),
    ALIASED_TYPE("aliased_type"),
    ALIAS_PATTERN("alias_pattern"),
    AND_OPERATOR("and_operator"),
    APPLICATION_EXPRESSION("application_expression"),
    ARRAY_BINDING_PATTERN("array_binding_pattern"),
    ARRAY_EXPRESSION("array_expression"),
    ARRAY_GET_EXPRESSION("array_get_expression"),
    ARRAY_PATTERN("array_pattern"),
    ASSERT_EXPRESSION("assert_expression"),
    ASSIGN_OPERATOR("assign_operator"),
    ATTRIBUTE("attribute"),
    ATTRIBUTE_ID("attribute_id"),
    ATTRIBUTE_PAYLOAD("attribute_payload"),
    BIGARRAY_GET_EXPRESSION("bigarray_get_expression"),
    BINDING_PATTERN("_binding_pattern"),
    BOOLEAN_("boolean"),
    CHARACTER("character"),
    CHARACTER_CONTENT("character_content"),
    CLASS_APPLICATION("class_application"),
    CLASS_BINDING("class_binding"),
    CLASS_BODY_TYPE("class_body_type"),
    CLASS_DEFINITION("class_definition"),
    CLASS_EXPRESSION("_class_expression"),
    CLASS_FIELD("_class_field"),
    CLASS_FIELD_SPECIFICATION("_class_field_specification"),
    CLASS_FUNCTION("class_function"),
    CLASS_FUNCTION_TYPE("class_function_type"),
    CLASS_INITIALIZER("class_initializer"),
    CLASS_NAME("class_name"),
    CLASS_PATH("class_path"),
    CLASS_TYPE("_class_type"),
    CLASS_TYPE_BINDING("class_type_binding"),
    CLASS_TYPE_DEFINITION("class_type_definition"),
    CLASS_TYPE_NAME("class_type_name"),
    CLASS_TYPE_PATH("class_type_path"),
    COERCION_EXPRESSION("coercion_expression"),
    COMMENT("comment"),
    COMPILATION_UNIT("compilation_unit"),
    CONCAT_OPERATOR("concat_operator"),
    CONSTANT("_constant"),
    CONSTRAIN_MODULE("constrain_module"),
    CONSTRAIN_MODULE_TYPE("constrain_module_type"),
    CONSTRAIN_TYPE("constrain_type"),
    CONSTRUCTED_TYPE("constructed_type"),
    CONSTRUCTOR_DECLARATION("constructor_declaration"),
    CONSTRUCTOR_NAME("constructor_name"),
    CONSTRUCTOR_PATH("constructor_path"),
    CONSTRUCTOR_PATTERN("constructor_pattern"),
    CONS_EXPRESSION("cons_expression"),
    CONS_PATTERN("cons_pattern"),
    CONVERSION_SPECIFICATION("conversion_specification"),
    DIRECTIVE("directive"),
    DO_CLAUSE("do_clause"),
    EFFECT_PATTERN("_effect_pattern"),
    EFFECT_PATTERN_2("effect_pattern"),
    ELSE_CLAUSE("else_clause"),
    ESCAPE_SEQUENCE("escape_sequence"),
    EXCEPTION_DEFINITION("exception_definition"),
    EXCEPTION_PATTERN("exception_pattern"),
    EXPRESSION("_expression"),
    EXPRESSION_ITEM("expression_item"),
    EXTENDED_MODULE_PATH("extended_module_path"),
    EXTENSION("extension"),
    EXTERNAL("external"),
    FIELD_DECLARATION("field_declaration"),
    FIELD_EXPRESSION("field_expression"),
    FIELD_GET_EXPRESSION("field_get_expression"),
    FIELD_NAME("field_name"),
    FIELD_PATH("field_path"),
    FIELD_PATTERN("field_pattern"),
    FLOATING_ATTRIBUTE("floating_attribute"),
    FOR_EXPRESSION("for_expression"),
    FUNCTION_EXPRESSION("function_expression"),
    FUNCTION_TYPE("function_type"),
    FUNCTOR("functor"),
    FUNCTOR_TYPE("functor_type"),
    FUN_EXPRESSION("fun_expression"),
    GUARD("guard"),
    HASH_EXPRESSION("hash_expression"),
    HASH_OPERATOR("hash_operator"),
    HASH_TYPE("hash_type"),
    IF_EXPRESSION("if_expression"),
    INCLUDE_MODULE("include_module"),
    INCLUDE_MODULE_TYPE("include_module_type"),
    INDEXING_OPERATOR("indexing_operator"),
    INDEXING_OPERATOR_PATH("indexing_operator_path"),
    INFIX_EXPRESSION("infix_expression"),
    INFIX_OPERATOR("_infix_operator"),
    INHERITANCE_DEFINITION("inheritance_definition"),
    INHERITANCE_SPECIFICATION("inheritance_specification"),
    INSTANCE_VARIABLE_DEFINITION("instance_variable_definition"),
    INSTANCE_VARIABLE_EXPRESSION("instance_variable_expression"),
    INSTANCE_VARIABLE_NAME("instance_variable_name"),
    INSTANCE_VARIABLE_SPECIFICATION("instance_variable_specification"),
    INSTANTIATED_CLASS("instantiated_class"),
    INSTANTIATED_CLASS_TYPE("instantiated_class_type"),
    ITEM_ATTRIBUTE("item_attribute"),
    ITEM_EXTENSION("item_extension"),
    LABELED_ARGUMENT("labeled_argument"),
    LABEL_NAME("label_name"),
    LAZY_EXPRESSION("lazy_expression"),
    LAZY_PATTERN("lazy_pattern"),
    LET_AND_OPERATOR("let_and_operator"),
    LET_BINDING("let_binding"),
    LET_CLASS_EXPRESSION("let_class_expression"),
    LET_EXCEPTION_EXPRESSION("let_exception_expression"),
    LET_EXPRESSION("let_expression"),
    LET_MODULE_EXPRESSION("let_module_expression"),
    LET_OPEN_CLASS_EXPRESSION("let_open_class_expression"),
    LET_OPEN_CLASS_TYPE("let_open_class_type"),
    LET_OPEN_EXPRESSION("let_open_expression"),
    LET_OPERATOR("let_operator"),
    LINE_NUMBER_DIRECTIVE("line_number_directive"),
    LIST_BINDING_PATTERN("list_binding_pattern"),
    LIST_EXPRESSION("list_expression"),
    LIST_PATTERN("list_pattern"),
    LOCAL_OPEN_EXPRESSION("local_open_expression"),
    LOCAL_OPEN_PATTERN("local_open_pattern"),
    LOCAL_OPEN_TYPE("local_open_type"),
    MATCH_CASE("match_case"),
    MATCH_EXPRESSION("match_expression"),
    MATCH_OPERATOR("match_operator"),
    METHOD_DEFINITION("method_definition"),
    METHOD_INVOCATION("method_invocation"),
    METHOD_NAME("method_name"),
    METHOD_SPECIFICATION("method_specification"),
    METHOD_TYPE("method_type"),
    MODULE_APPLICATION("module_application"),
    MODULE_BINDING("module_binding"),
    MODULE_DEFINITION("module_definition"),
    MODULE_EXPRESSION("_module_expression"),
    MODULE_NAME("module_name"),
    MODULE_PARAMETER("module_parameter"),
    MODULE_PATH("module_path"),
    MODULE_TYPE("_module_type"),
    MODULE_TYPE_CONSTRAINT("module_type_constraint"),
    MODULE_TYPE_DEFINITION("module_type_definition"),
    MODULE_TYPE_NAME("module_type_name"),
    MODULE_TYPE_OF("module_type_of"),
    MODULE_TYPE_PATH("module_type_path"),
    MULT_OPERATOR("mult_operator"),
    NEW_EXPRESSION("new_expression"),
    NUMBER("number"),
    OBJECT_COPY_EXPRESSION("object_copy_expression"),
    OBJECT_EXPRESSION("object_expression"),
    OBJECT_TYPE("object_type"),
    OCAMLYACC_VALUE("ocamlyacc_value"),
    OPEN_MODULE("open_module"),
    OR_OPERATOR("or_operator"),
    OR_PATTERN("or_pattern"),
    PACKAGE_EXPRESSION("package_expression"),
    PACKAGE_PATTERN("package_pattern"),
    PACKAGE_TYPE("package_type"),
    PACKED_MODULE("packed_module"),
    PARAMETER("_parameter"),
    PARAMETER_2("parameter"),
    PARENTHESIZED_CLASS_EXPRESSION("parenthesized_class_expression"),
    PARENTHESIZED_EXPRESSION("parenthesized_expression"),
    PARENTHESIZED_MODULE_EXPRESSION("parenthesized_module_expression"),
    PARENTHESIZED_MODULE_TYPE("parenthesized_module_type"),
    PARENTHESIZED_OPERATOR("parenthesized_operator"),
    PARENTHESIZED_PATTERN("parenthesized_pattern"),
    PARENTHESIZED_TYPE("parenthesized_type"),
    PATTERN("_pattern"),
    POLYMORPHIC_TYPE("_polymorphic_type"),
    POLYMORPHIC_TYPE_2("polymorphic_type"),
    POLYMORPHIC_VARIANT_PATTERN("polymorphic_variant_pattern"),
    POLYMORPHIC_VARIANT_TYPE("polymorphic_variant_type"),
    POW_OPERATOR("pow_operator"),
    PREFIX_EXPRESSION("prefix_expression"),
    PREFIX_OPERATOR("prefix_operator"),
    PRETTY_PRINTING_INDICATION("pretty_printing_indication"),
    PRODUCT_EXPRESSION("product_expression"),
    QUOTED_EXTENSION("quoted_extension"),
    QUOTED_ITEM_EXTENSION("quoted_item_extension"),
    QUOTED_STRING("quoted_string"),
    QUOTED_STRING_CONTENT("quoted_string_content"),
    RANGE_PATTERN("range_pattern"),
    RECORD_BINDING_PATTERN("record_binding_pattern"),
    RECORD_DECLARATION("record_declaration"),
    RECORD_EXPRESSION("record_expression"),
    RECORD_PATTERN("record_pattern"),
    REFUTATION_CASE("refutation_case"),
    REL_OPERATOR("rel_operator"),
    SEQUENCE_EXPRESSION("_sequence_expression"),
    SEQUENCE_EXPRESSION_2("sequence_expression"),
    SET_EXPRESSION("set_expression"),
    SHEBANG("shebang"),
    SIGNATURE("signature"),
    SIGNATURE_ITEM("_signature_item"),
    SIGNED_CONSTANT("_signed_constant"),
    SIGNED_NUMBER("signed_number"),
    SIGN_EXPRESSION("sign_expression"),
    SIGN_OPERATOR("sign_operator"),
    SIMPLE_CLASS_EXPRESSION("_simple_class_expression"),
    SIMPLE_CLASS_TYPE("_simple_class_type"),
    SIMPLE_EXPRESSION("_simple_expression"),
    SIMPLE_MODULE_EXPRESSION("_simple_module_expression"),
    SIMPLE_PATTERN("_simple_pattern"),
    SIMPLE_TYPE("_simple_type"),
    STRING("string"),
    STRING_CONTENT("string_content"),
    STRING_GET_EXPRESSION("string_get_expression"),
    STRUCTURE("structure"),
    STRUCTURE_ITEM("_structure_item"),
    TAG("tag"),
    TAG_PATTERN("tag_pattern"),
    TAG_SPECIFICATION("tag_specification"),
    THEN_CLAUSE("then_clause"),
    TOPLEVEL_DIRECTIVE("toplevel_directive"),
    TRY_EXPRESSION("try_expression"),
    TUPLE_PATTERN("tuple_pattern"),
    TUPLE_TYPE("_tuple_type"),
    TUPLE_TYPE_2("tuple_type"),
    TYPE("_type"),
    TYPED_CLASS_EXPRESSION("typed_class_expression"),
    TYPED_EXPRESSION("typed_expression"),
    TYPED_LABEL("typed_label"),
    TYPED_MODULE_EXPRESSION("typed_module_expression"),
    TYPED_PATTERN("typed_pattern"),
    TYPE_BINDING("type_binding"),
    TYPE_CONSTRAINT("type_constraint"),
    TYPE_CONSTRUCTOR("type_constructor"),
    TYPE_CONSTRUCTOR_PATH("type_constructor_path"),
    TYPE_DEFINITION("type_definition"),
    TYPE_PARAMETER_CONSTRAINT("type_parameter_constraint"),
    TYPE_VARIABLE("type_variable"),
    UNIT("unit"),
    VALUE_DEFINITION("value_definition"),
    VALUE_NAME("value_name"),
    VALUE_PATH("value_path"),
    VALUE_PATTERN("value_pattern"),
    VALUE_SPECIFICATION("value_specification"),
    VARIANT_DECLARATION("variant_declaration"),
    WHILE_EXPRESSION("while_expression");

    public static final Set<OcamlNodeType> BINDING_PATTERN_SET = Set.of(
            ALIAS_PATTERN,
            ARRAY_PATTERN,
            CONSTRUCTOR_PATH,
            CONSTRUCTOR_PATTERN,
            CONS_PATTERN,
            EXTENSION,
            LAZY_PATTERN,
            LIST_PATTERN,
            LOCAL_OPEN_PATTERN,
            OR_PATTERN,
            PACKAGE_PATTERN,
            PARENTHESIZED_OPERATOR,
            PARENTHESIZED_PATTERN,
            POLYMORPHIC_VARIANT_PATTERN,
            QUOTED_EXTENSION,
            RANGE_PATTERN,
            RECORD_PATTERN,
            SIGNED_CONSTANT,
            TAG,
            TAG_PATTERN,
            TUPLE_PATTERN,
            TYPED_PATTERN,
            VALUE_NAME);
    public static final Set<OcamlNodeType> CLASS_EXPRESSION_SET = Set.of(
            CLASS_APPLICATION,
            CLASS_FUNCTION,
            LET_CLASS_EXPRESSION,
            LET_OPEN_CLASS_EXPRESSION,
            SIMPLE_CLASS_EXPRESSION);
    public static final Set<OcamlNodeType> CLASS_FIELD_SET = Set.of(
            CLASS_INITIALIZER,
            INHERITANCE_DEFINITION,
            INSTANCE_VARIABLE_DEFINITION,
            ITEM_EXTENSION,
            METHOD_DEFINITION,
            QUOTED_ITEM_EXTENSION,
            TYPE_PARAMETER_CONSTRAINT);
    public static final Set<OcamlNodeType> CLASS_FIELD_SPECIFICATION_SET = Set.of(
            INHERITANCE_SPECIFICATION,
            INSTANCE_VARIABLE_SPECIFICATION,
            ITEM_EXTENSION,
            METHOD_SPECIFICATION,
            QUOTED_ITEM_EXTENSION,
            TYPE_PARAMETER_CONSTRAINT);
    public static final Set<OcamlNodeType> CLASS_TYPE_SET = Set.of(CLASS_FUNCTION_TYPE, SIMPLE_CLASS_TYPE);
    public static final Set<OcamlNodeType> CONSTANT_SET =
            Set.of(BOOLEAN_, CHARACTER, NUMBER, QUOTED_STRING, STRING, UNIT);
    public static final Set<OcamlNodeType> EFFECT_PATTERN_SET =
            Set.of(CONSTRUCTOR_PATTERN, LAZY_PATTERN, SIMPLE_PATTERN, TAG_PATTERN);
    public static final Set<OcamlNodeType> EXPRESSION_SET = Set.of(
            APPLICATION_EXPRESSION,
            ASSERT_EXPRESSION,
            CONS_EXPRESSION,
            FOR_EXPRESSION,
            FUNCTION_EXPRESSION,
            FUN_EXPRESSION,
            IF_EXPRESSION,
            INFIX_EXPRESSION,
            LAZY_EXPRESSION,
            LET_EXCEPTION_EXPRESSION,
            LET_EXPRESSION,
            LET_MODULE_EXPRESSION,
            LET_OPEN_EXPRESSION,
            MATCH_EXPRESSION,
            PRODUCT_EXPRESSION,
            SET_EXPRESSION,
            SIGN_EXPRESSION,
            SIMPLE_EXPRESSION,
            TRY_EXPRESSION,
            WHILE_EXPRESSION);
    public static final Set<OcamlNodeType> INFIX_OPERATOR_SET = Set.of(
            ADD_OPERATOR,
            AND_OPERATOR,
            ASSIGN_OPERATOR,
            CONCAT_OPERATOR,
            MULT_OPERATOR,
            OR_OPERATOR,
            POW_OPERATOR,
            REL_OPERATOR);
    public static final Set<OcamlNodeType> MODULE_EXPRESSION_SET =
            Set.of(FUNCTOR, MODULE_APPLICATION, MODULE_PATH, SIMPLE_MODULE_EXPRESSION, STRUCTURE);
    public static final Set<OcamlNodeType> MODULE_TYPE_SET = Set.of(
            EXTENSION,
            FUNCTOR_TYPE,
            MODULE_TYPE_CONSTRAINT,
            MODULE_TYPE_OF,
            MODULE_TYPE_PATH,
            PARENTHESIZED_MODULE_TYPE,
            QUOTED_EXTENSION,
            SIGNATURE);
    public static final Set<OcamlNodeType> PARAMETER_SET = Set.of(ABSTRACT_TYPE, PARAMETER_2);
    public static final Set<OcamlNodeType> PATTERN_SET = Set.of(
            ALIAS_PATTERN,
            CONS_PATTERN,
            EFFECT_PATTERN,
            EFFECT_PATTERN_2,
            EXCEPTION_PATTERN,
            OR_PATTERN,
            RANGE_PATTERN,
            TUPLE_PATTERN);
    public static final Set<OcamlNodeType> POLYMORPHIC_TYPE_SET = Set.of(POLYMORPHIC_TYPE_2, TYPE);
    public static final Set<OcamlNodeType> SEQUENCE_EXPRESSION_SET = Set.of(EXPRESSION, SEQUENCE_EXPRESSION_2);
    public static final Set<OcamlNodeType> SIGNATURE_ITEM_SET = Set.of(
            CLASS_DEFINITION,
            CLASS_TYPE_DEFINITION,
            EXCEPTION_DEFINITION,
            EXTERNAL,
            FLOATING_ATTRIBUTE,
            INCLUDE_MODULE_TYPE,
            ITEM_EXTENSION,
            MODULE_DEFINITION,
            MODULE_TYPE_DEFINITION,
            OPEN_MODULE,
            QUOTED_ITEM_EXTENSION,
            TYPE_DEFINITION,
            VALUE_SPECIFICATION);
    public static final Set<OcamlNodeType> SIGNED_CONSTANT_SET = Set.of(CONSTANT, SIGNED_NUMBER);
    public static final Set<OcamlNodeType> SIMPLE_CLASS_EXPRESSION_SET = Set.of(
            CLASS_PATH,
            EXTENSION,
            INSTANTIATED_CLASS,
            OBJECT_EXPRESSION,
            PARENTHESIZED_CLASS_EXPRESSION,
            QUOTED_EXTENSION,
            TYPED_CLASS_EXPRESSION);
    public static final Set<OcamlNodeType> SIMPLE_CLASS_TYPE_SET = Set.of(
            CLASS_BODY_TYPE,
            CLASS_TYPE_PATH,
            EXTENSION,
            INSTANTIATED_CLASS_TYPE,
            LET_OPEN_CLASS_TYPE,
            QUOTED_EXTENSION);
    public static final Set<OcamlNodeType> SIMPLE_EXPRESSION_SET = Set.of(
            ARRAY_EXPRESSION,
            ARRAY_GET_EXPRESSION,
            BIGARRAY_GET_EXPRESSION,
            COERCION_EXPRESSION,
            CONSTANT,
            CONSTRUCTOR_PATH,
            EXTENSION,
            FIELD_GET_EXPRESSION,
            HASH_EXPRESSION,
            LIST_EXPRESSION,
            LOCAL_OPEN_EXPRESSION,
            METHOD_INVOCATION,
            NEW_EXPRESSION,
            OBJECT_COPY_EXPRESSION,
            OBJECT_EXPRESSION,
            OCAMLYACC_VALUE,
            PACKAGE_EXPRESSION,
            PARENTHESIZED_EXPRESSION,
            PREFIX_EXPRESSION,
            QUOTED_EXTENSION,
            RECORD_EXPRESSION,
            STRING_GET_EXPRESSION,
            TAG,
            TYPED_EXPRESSION,
            VALUE_PATH);
    public static final Set<OcamlNodeType> SIMPLE_MODULE_EXPRESSION_SET = Set.of(
            EXTENSION, PACKED_MODULE, PARENTHESIZED_MODULE_EXPRESSION, QUOTED_EXTENSION, TYPED_MODULE_EXPRESSION);
    public static final Set<OcamlNodeType> SIMPLE_PATTERN_SET = Set.of(
            ARRAY_PATTERN,
            CONSTRUCTOR_PATH,
            EXTENSION,
            LIST_PATTERN,
            LOCAL_OPEN_PATTERN,
            PACKAGE_PATTERN,
            PARENTHESIZED_OPERATOR,
            PARENTHESIZED_PATTERN,
            POLYMORPHIC_VARIANT_PATTERN,
            QUOTED_EXTENSION,
            RECORD_PATTERN,
            SIGNED_CONSTANT,
            TAG,
            TYPED_PATTERN,
            VALUE_PATTERN);
    public static final Set<OcamlNodeType> SIMPLE_TYPE_SET = Set.of(
            CONSTRUCTED_TYPE,
            EXTENSION,
            HASH_TYPE,
            LOCAL_OPEN_TYPE,
            OBJECT_TYPE,
            PACKAGE_TYPE,
            PARENTHESIZED_TYPE,
            POLYMORPHIC_VARIANT_TYPE,
            QUOTED_EXTENSION,
            TYPE_CONSTRUCTOR_PATH,
            TYPE_VARIABLE);
    public static final Set<OcamlNodeType> STRUCTURE_ITEM_SET = Set.of(
            CLASS_DEFINITION,
            CLASS_TYPE_DEFINITION,
            EXCEPTION_DEFINITION,
            EXTERNAL,
            FLOATING_ATTRIBUTE,
            INCLUDE_MODULE,
            ITEM_EXTENSION,
            MODULE_DEFINITION,
            MODULE_TYPE_DEFINITION,
            OPEN_MODULE,
            QUOTED_ITEM_EXTENSION,
            TYPE_DEFINITION,
            VALUE_DEFINITION);
    public static final Set<OcamlNodeType> TUPLE_TYPE_SET = Set.of(SIMPLE_TYPE, TUPLE_TYPE_2);
    public static final Set<OcamlNodeType> TYPE_SET = Set.of(ALIASED_TYPE, FUNCTION_TYPE, TUPLE_TYPE);

    private final @Nullable String type;

    OcamlNodeType(@Nullable String type) {
        this.type = type;
    }

    public @Nullable String getType() {
        return type;
    }

    public static OcamlNodeType from(@Nullable TSNode node) {
        if (node == null) return __NULL__;
        return fromType(node.getType());
    }

    public static OcamlNodeType fromType(@Nullable String type) {
        if (type == null) return __NULL__;
        OcamlNodeType t = LOOKUP.get(type);
        return t == null ? __NULL__ : t;
    }

    private static final Map<String, OcamlNodeType> LOOKUP = initLookup();

    private static Map<String, OcamlNodeType> initLookup() {
        HashMap<String, OcamlNodeType> m = new HashMap<>();
        for (OcamlNodeType t : values()) {
            if (t.type != null) m.put(t.type, t);
        }
        return Collections.unmodifiableMap(m);
    }
}
